// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

public enum ClientContent : byte
{
  NONE = 0,
  names = 1,
  list = 2,
  search = 3,
  update = 4,
  delete = 5,
};

public class ClientContentUnion {
  public ClientContent Type { get; set; }
  public object Value { get; set; }

  public ClientContentUnion() {
    this.Type = ClientContent.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public CardGameUtils.Packets.Deck.ClientNamesPacketT Asnames() { return this.As<CardGameUtils.Packets.Deck.ClientNamesPacketT>(); }
  public static ClientContentUnion Fromnames(CardGameUtils.Packets.Deck.ClientNamesPacketT _names) { return new ClientContentUnion{ Type = ClientContent.names, Value = _names }; }
  public CardGameUtils.Packets.Deck.ClientListPacketT Aslist() { return this.As<CardGameUtils.Packets.Deck.ClientListPacketT>(); }
  public static ClientContentUnion Fromlist(CardGameUtils.Packets.Deck.ClientListPacketT _list) { return new ClientContentUnion{ Type = ClientContent.list, Value = _list }; }
  public CardGameUtils.Packets.Deck.ClientSearchPacketT Assearch() { return this.As<CardGameUtils.Packets.Deck.ClientSearchPacketT>(); }
  public static ClientContentUnion Fromsearch(CardGameUtils.Packets.Deck.ClientSearchPacketT _search) { return new ClientContentUnion{ Type = ClientContent.search, Value = _search }; }
  public CardGameUtils.Packets.Deck.ClientUpdatePacketT Asupdate() { return this.As<CardGameUtils.Packets.Deck.ClientUpdatePacketT>(); }
  public static ClientContentUnion Fromupdate(CardGameUtils.Packets.Deck.ClientUpdatePacketT _update) { return new ClientContentUnion{ Type = ClientContent.update, Value = _update }; }
  public CardGameUtils.Packets.Deck.ClientDeletePacketT Asdelete() { return this.As<CardGameUtils.Packets.Deck.ClientDeletePacketT>(); }
  public static ClientContentUnion Fromdelete(CardGameUtils.Packets.Deck.ClientDeletePacketT _delete) { return new ClientContentUnion{ Type = ClientContent.delete, Value = _delete }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ClientContentUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ClientContent.names: return CardGameUtils.Packets.Deck.ClientNamesPacket.Pack(builder, _o.Asnames()).Value;
      case ClientContent.list: return CardGameUtils.Packets.Deck.ClientListPacket.Pack(builder, _o.Aslist()).Value;
      case ClientContent.search: return CardGameUtils.Packets.Deck.ClientSearchPacket.Pack(builder, _o.Assearch()).Value;
      case ClientContent.update: return CardGameUtils.Packets.Deck.ClientUpdatePacket.Pack(builder, _o.Asupdate()).Value;
      case ClientContent.delete: return CardGameUtils.Packets.Deck.ClientDeletePacket.Pack(builder, _o.Asdelete()).Value;
    }
  }
}



static public class ClientContentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ClientContent)typeId)
    {
      case ClientContent.names:
        result = CardGameUtils.Packets.Deck.ClientNamesPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.list:
        result = CardGameUtils.Packets.Deck.ClientListPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.search:
        result = CardGameUtils.Packets.Deck.ClientSearchPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.update:
        result = CardGameUtils.Packets.Deck.ClientUpdatePacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.delete:
        result = CardGameUtils.Packets.Deck.ClientDeletePacketVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
