// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientSearchPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientSearchPacket GetRootAsClientSearchPacket(ByteBuffer _bb) { return GetRootAsClientSearchPacket(_bb, new ClientSearchPacket()); }
  public static ClientSearchPacket GetRootAsClientSearchPacket(ByteBuffer _bb, ClientSearchPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientSearchPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Filter { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilterBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilterBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilterArray() { return __p.__vector_as_array<byte>(4); }
  public CardGameUtils.Constants.PlayerClass PlayerClass { get { int o = __p.__offset(6); return o != 0 ? (CardGameUtils.Constants.PlayerClass)__p.bb.GetSbyte(o + __p.bb_pos) : CardGameUtils.Constants.PlayerClass.UNKNOWN; } }
  public bool IncludeGenericCards { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<CardGameUtils.Packets.Deck.ClientSearchPacket> CreateClientSearchPacket(FlatBufferBuilder builder,
      StringOffset filterOffset = default(StringOffset),
      CardGameUtils.Constants.PlayerClass player_class = CardGameUtils.Constants.PlayerClass.UNKNOWN,
      bool include_generic_cards = false) {
    builder.StartTable(3);
    ClientSearchPacket.AddFilter(builder, filterOffset);
    ClientSearchPacket.AddIncludeGenericCards(builder, include_generic_cards);
    ClientSearchPacket.AddPlayerClass(builder, player_class);
    return ClientSearchPacket.EndClientSearchPacket(builder);
  }

  public static void StartClientSearchPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddFilter(FlatBufferBuilder builder, StringOffset filterOffset) { builder.AddOffset(0, filterOffset.Value, 0); }
  public static void AddPlayerClass(FlatBufferBuilder builder, CardGameUtils.Constants.PlayerClass playerClass) { builder.AddSbyte(1, (sbyte)playerClass, 0); }
  public static void AddIncludeGenericCards(FlatBufferBuilder builder, bool includeGenericCards) { builder.AddBool(2, includeGenericCards, false); }
  public static Offset<CardGameUtils.Packets.Deck.ClientSearchPacket> EndClientSearchPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Deck.ClientSearchPacket>(o);
  }
  public ClientSearchPacketT UnPack() {
    var _o = new ClientSearchPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientSearchPacketT _o) {
    _o.Filter = this.Filter;
    _o.PlayerClass = this.PlayerClass;
    _o.IncludeGenericCards = this.IncludeGenericCards;
  }
  public static Offset<CardGameUtils.Packets.Deck.ClientSearchPacket> Pack(FlatBufferBuilder builder, ClientSearchPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Deck.ClientSearchPacket>);
    var _filter = _o.Filter == null ? default(StringOffset) : builder.CreateString(_o.Filter);
    return CreateClientSearchPacket(
      builder,
      _filter,
      _o.PlayerClass,
      _o.IncludeGenericCards);
  }
}

public class ClientSearchPacketT
{
  public string Filter { get; set; }
  public CardGameUtils.Constants.PlayerClass PlayerClass { get; set; }
  public bool IncludeGenericCards { get; set; }

  public ClientSearchPacketT() {
    this.Filter = null;
    this.PlayerClass = CardGameUtils.Constants.PlayerClass.UNKNOWN;
    this.IncludeGenericCards = false;
  }
}


static public class ClientSearchPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Filter*/, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerClass*/, 1 /*CardGameUtils.Constants.PlayerClass*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*IncludeGenericCards*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
