// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientNamesPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientNamesPacket GetRootAsClientNamesPacket(ByteBuffer _bb) { return GetRootAsClientNamesPacket(_bb, new ClientNamesPacket()); }
  public static ClientNamesPacket GetRootAsClientNamesPacket(ByteBuffer _bb, ClientNamesPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientNamesPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartClientNamesPacket(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<CardGameUtils.Packets.Deck.ClientNamesPacket> EndClientNamesPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Deck.ClientNamesPacket>(o);
  }
  public ClientNamesPacketT UnPack() {
    var _o = new ClientNamesPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientNamesPacketT _o) {
  }
  public static Offset<CardGameUtils.Packets.Deck.ClientNamesPacket> Pack(FlatBufferBuilder builder, ClientNamesPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Deck.ClientNamesPacket>);
    StartClientNamesPacket(builder);
    return EndClientNamesPacket(builder);
  }
}

public class ClientNamesPacketT
{

  public ClientNamesPacketT() {
  }
}


static public class ClientNamesPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
