// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

public enum ServerContent : byte
{
  NONE = 0,
  names = 1,
  list = 2,
  search = 3,
};

public class ServerContentUnion {
  public ServerContent Type { get; set; }
  public object Value { get; set; }

  public ServerContentUnion() {
    this.Type = ServerContent.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public CardGameUtils.Packets.Deck.ServerNamesPacketT Asnames() { return this.As<CardGameUtils.Packets.Deck.ServerNamesPacketT>(); }
  public static ServerContentUnion Fromnames(CardGameUtils.Packets.Deck.ServerNamesPacketT _names) { return new ServerContentUnion{ Type = ServerContent.names, Value = _names }; }
  public CardGameUtils.Packets.Deck.ServerListPacketT Aslist() { return this.As<CardGameUtils.Packets.Deck.ServerListPacketT>(); }
  public static ServerContentUnion Fromlist(CardGameUtils.Packets.Deck.ServerListPacketT _list) { return new ServerContentUnion{ Type = ServerContent.list, Value = _list }; }
  public CardGameUtils.Packets.Deck.ServerSearchPacketT Assearch() { return this.As<CardGameUtils.Packets.Deck.ServerSearchPacketT>(); }
  public static ServerContentUnion Fromsearch(CardGameUtils.Packets.Deck.ServerSearchPacketT _search) { return new ServerContentUnion{ Type = ServerContent.search, Value = _search }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ServerContentUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ServerContent.names: return CardGameUtils.Packets.Deck.ServerNamesPacket.Pack(builder, _o.Asnames()).Value;
      case ServerContent.list: return CardGameUtils.Packets.Deck.ServerListPacket.Pack(builder, _o.Aslist()).Value;
      case ServerContent.search: return CardGameUtils.Packets.Deck.ServerSearchPacket.Pack(builder, _o.Assearch()).Value;
    }
  }
}



static public class ServerContentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ServerContent)typeId)
    {
      case ServerContent.names:
        result = CardGameUtils.Packets.Deck.ServerNamesPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.list:
        result = CardGameUtils.Packets.Deck.ServerListPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.search:
        result = CardGameUtils.Packets.Deck.ServerSearchPacketVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
