// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerNamesPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerNamesPacket GetRootAsServerNamesPacket(ByteBuffer _bb) { return GetRootAsServerNamesPacket(_bb, new ServerNamesPacket()); }
  public static ServerNamesPacket GetRootAsServerNamesPacket(ByteBuffer _bb, ServerNamesPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerNamesPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Names(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int NamesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CardGameUtils.Packets.Deck.ServerNamesPacket> CreateServerNamesPacket(FlatBufferBuilder builder,
      VectorOffset namesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ServerNamesPacket.AddNames(builder, namesOffset);
    return ServerNamesPacket.EndServerNamesPacket(builder);
  }

  public static void StartServerNamesPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddNames(FlatBufferBuilder builder, VectorOffset namesOffset) { builder.AddOffset(0, namesOffset.Value, 0); }
  public static VectorOffset CreateNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNamesVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNamesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Deck.ServerNamesPacket> EndServerNamesPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Deck.ServerNamesPacket>(o);
  }
  public ServerNamesPacketT UnPack() {
    var _o = new ServerNamesPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerNamesPacketT _o) {
    _o.Names = new List<string>();
    for (var _j = 0; _j < this.NamesLength; ++_j) {_o.Names.Add(this.Names(_j));}
  }
  public static Offset<CardGameUtils.Packets.Deck.ServerNamesPacket> Pack(FlatBufferBuilder builder, ServerNamesPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Deck.ServerNamesPacket>);
    var _names = default(VectorOffset);
    if (_o.Names != null) {
      var __names = new StringOffset[_o.Names.Count];
      for (var _j = 0; _j < __names.Length; ++_j) { __names[_j] = builder.CreateString(_o.Names[_j]); }
      _names = CreateNamesVector(builder, __names);
    }
    return CreateServerNamesPacket(
      builder,
      _names);
  }
}

public class ServerNamesPacketT
{
  public List<string> Names { get; set; }

  public ServerNamesPacketT() {
    this.Names = null;
  }
}


static public class ServerNamesPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*Names*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
