// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Deck
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerPacket GetRootAsServerPacket(ByteBuffer _bb) { return GetRootAsServerPacket(_bb, new ServerPacket()); }
  public static ServerPacket GetRootAsServerPacket(ByteBuffer _bb, ServerPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ServerPacketBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "deck"); }
  public static bool VerifyServerPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("deck", false, ServerPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Packets.Deck.ServerContent ContentType { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Packets.Deck.ServerContent)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Packets.Deck.ServerContent.NONE; } }
  public TTable? Content<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public CardGameUtils.Packets.Deck.ServerNamesPacket ContentAsnames() { return Content<CardGameUtils.Packets.Deck.ServerNamesPacket>().Value; }
  public CardGameUtils.Packets.Deck.ServerListPacket ContentAslist() { return Content<CardGameUtils.Packets.Deck.ServerListPacket>().Value; }
  public CardGameUtils.Packets.Deck.ServerSearchPacket ContentAssearch() { return Content<CardGameUtils.Packets.Deck.ServerSearchPacket>().Value; }

  public static Offset<CardGameUtils.Packets.Deck.ServerPacket> CreateServerPacket(FlatBufferBuilder builder,
      CardGameUtils.Packets.Deck.ServerContent content_type = CardGameUtils.Packets.Deck.ServerContent.NONE,
      int contentOffset = 0) {
    builder.StartTable(2);
    ServerPacket.AddContent(builder, contentOffset);
    ServerPacket.AddContentType(builder, content_type);
    return ServerPacket.EndServerPacket(builder);
  }

  public static void StartServerPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddContentType(FlatBufferBuilder builder, CardGameUtils.Packets.Deck.ServerContent contentType) { builder.AddByte(0, (byte)contentType, 0); }
  public static void AddContent(FlatBufferBuilder builder, int contentOffset) { builder.AddOffset(1, contentOffset, 0); }
  public static Offset<CardGameUtils.Packets.Deck.ServerPacket> EndServerPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Deck.ServerPacket>(o);
  }
  public static void FinishServerPacketBuffer(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Deck.ServerPacket> offset) { builder.Finish(offset.Value, "deck"); }
  public static void FinishSizePrefixedServerPacketBuffer(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Deck.ServerPacket> offset) { builder.FinishSizePrefixed(offset.Value, "deck"); }
  public ServerPacketT UnPack() {
    var _o = new ServerPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerPacketT _o) {
    _o.Content = new CardGameUtils.Packets.Deck.ServerContentUnion();
    _o.Content.Type = this.ContentType;
    switch (this.ContentType) {
      default: break;
      case CardGameUtils.Packets.Deck.ServerContent.names:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Deck.ServerNamesPacket>().HasValue ? this.Content<CardGameUtils.Packets.Deck.ServerNamesPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Deck.ServerContent.list:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Deck.ServerListPacket>().HasValue ? this.Content<CardGameUtils.Packets.Deck.ServerListPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Deck.ServerContent.search:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Deck.ServerSearchPacket>().HasValue ? this.Content<CardGameUtils.Packets.Deck.ServerSearchPacket>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<CardGameUtils.Packets.Deck.ServerPacket> Pack(FlatBufferBuilder builder, ServerPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Deck.ServerPacket>);
    var _content_type = _o.Content == null ? CardGameUtils.Packets.Deck.ServerContent.NONE : _o.Content.Type;
    var _content = _o.Content == null ? 0 : CardGameUtils.Packets.Deck.ServerContentUnion.Pack(builder, _o.Content);
    return CreateServerPacket(
      builder,
      _content_type,
      _content);
  }
}

public class ServerPacketT
{
  public CardGameUtils.Packets.Deck.ServerContentUnion Content { get; set; }

  public ServerPacketT() {
    this.Content = null;
  }
  public static ServerPacketT DeserializeFromBinary(byte[] fbBuffer) {
    return ServerPacket.GetRootAsServerPacket(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ServerPacket.FinishServerPacketBuffer(fbb, ServerPacket.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class ServerPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ContentType*/, 1 /*CardGameUtils.Packets.Deck.ServerContent*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Content*/, CardGameUtils.Packets.Deck.ServerContentVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
