/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ClientSelectZone : TBase
	{
		private int _zone;

		public int Zone
		{
			get
			{
				return _zone;
			}
			set
			{
				__isset.@zone = true;
				this._zone = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @zone;
		}

		public ClientSelectZone()
		{
		}

		public ClientSelectZone DeepCopy()
		{
			var tmp66 = new ClientSelectZone()
			{
			};
			if(__isset.@zone)
			{
				tmp66.Zone = this.Zone;
			}
			tmp66.__isset.@zone = this.__isset.@zone;
			return tmp66;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I32)
							{
								Zone = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp67 = new TStruct("ClientSelectZone");
				await oprot.WriteStructBeginAsync(tmp67, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp68 = new TField();
				if(__isset.@zone)
				{
					tmp68.Name = "zone";
					tmp68.Type = TType.I32;
					tmp68.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp68, cancellationToken);
					await oprot.WriteI32Async(Zone, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientSelectZone other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@zone == other.__isset.@zone) && ((!__isset.@zone) || (Equals(Zone, other.Zone))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@zone)
				{
					hashcode = (hashcode * 397) + Zone.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp69 = new StringBuilder("ClientSelectZone(");
			int tmp70 = 0;
			if(__isset.@zone)
			{
				if(0 < tmp70++) { _ = tmp69.Append(", "); }
				_ = tmp69.Append("Zone: ");
				Zone.ToString(tmp69);
			}
			_ = tmp69.Append(')');
			return tmp69.ToString();
		}
	}

}
