/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ClientCustomSelectCardsIntermediate : TBase
	{
		private List<int>? _uids;

		public List<int>? Uids
		{
			get
			{
				return _uids;
			}
			set
			{
				__isset.@uids = true;
				this._uids = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @uids;
		}

		public ClientCustomSelectCardsIntermediate()
		{
		}

		public ClientCustomSelectCardsIntermediate DeepCopy()
		{
			var tmp48 = new ClientCustomSelectCardsIntermediate()
			{
			};
			if((Uids != null) && __isset.@uids)
			{
				tmp48.Uids = this.Uids.DeepCopy()!;
			}
			tmp48.__isset.@uids = this.__isset.@uids;
			return tmp48;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.List)
							{
								{
									var _list49 = await iprot.ReadListBeginAsync(cancellationToken);
									Uids = new List<int>(_list49.Count);
									for(int _i50 = 0; _i50 < _list49.Count; ++_i50)
									{
										int _elem51;
										_elem51 = await iprot.ReadI32Async(cancellationToken);
										Uids.Add(_elem51);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp52 = new TStruct("ClientCustomSelectCardsIntermediate");
				await oprot.WriteStructBeginAsync(tmp52, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp53 = new TField();
				if((Uids != null) && __isset.@uids)
				{
					tmp53.Name = "uids";
					tmp53.Type = TType.List;
					tmp53.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp53, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.I32, Uids.Count), cancellationToken);
					foreach(int _iter54 in Uids)
					{
						await oprot.WriteI32Async(_iter54, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientCustomSelectCardsIntermediate other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@uids == other.__isset.@uids) && ((!__isset.@uids) || (TCollections.Equals(Uids, other.Uids))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Uids != null) && __isset.@uids)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Uids);
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp55 = new StringBuilder("ClientCustomSelectCardsIntermediate(");
			int tmp56 = 0;
			if((Uids != null) && __isset.@uids)
			{
				if(0 < tmp56++) { _ = tmp55.Append(", "); }
				_ = tmp55.Append("Uids: ");
				Uids.ToString(tmp55);
			}
			_ = tmp55.Append(')');
			return tmp55.ToString();
		}
	}

}
