/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ClientShowGrave : TBase
	{
		private bool _of_opponent;

		public bool Of_opponent
		{
			get
			{
				return _of_opponent;
			}
			set
			{
				__isset.of_opponent = true;
				this._of_opponent = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool of_opponent;
		}

		public ClientShowGrave()
		{
		}

		public ClientShowGrave DeepCopy()
		{
			var tmp61 = new ClientShowGrave()
			{
			};
			if(__isset.of_opponent)
			{
				tmp61.Of_opponent = this.Of_opponent;
			}
			tmp61.__isset.of_opponent = this.__isset.of_opponent;
			return tmp61;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Bool)
							{
								Of_opponent = await iprot.ReadBoolAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp62 = new TStruct("ClientShowGrave");
				await oprot.WriteStructBeginAsync(tmp62, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp63 = new TField();
				if(__isset.of_opponent)
				{
					tmp63.Name = "of_opponent";
					tmp63.Type = TType.Bool;
					tmp63.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp63, cancellationToken);
					await oprot.WriteBoolAsync(Of_opponent, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientShowGrave other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.of_opponent == other.__isset.of_opponent) && ((!__isset.of_opponent) || (Equals(Of_opponent, other.Of_opponent))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.of_opponent)
				{
					hashcode = (hashcode * 397) + Of_opponent.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp64 = new StringBuilder("ClientShowGrave(");
			int tmp65 = 0;
			if(__isset.of_opponent)
			{
				if(0 < tmp65++) { _ = tmp64.Append(", "); }
				_ = tmp64.Append("Of_opponent: ");
				Of_opponent.ToString(tmp64);
			}
			_ = tmp64.Append(')');
			return tmp64.ToString();
		}
	}

}
