/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ClientSelectOption : TBase
	{
		private Constants.Location _location;
		private int _uid;
		private CardAction? _action;

		/// <summary>
		/// 
		/// <seealso cref="Constants.Location"/>
		/// </summary>
		public Constants.Location Location
		{
			get
			{
				return _location;
			}
			set
			{
				__isset.@location = true;
				this._location = value;
			}
		}

		public int Uid
		{
			get
			{
				return _uid;
			}
			set
			{
				__isset.@uid = true;
				this._uid = value;
			}
		}

		public CardAction? Action
		{
			get
			{
				return _action;
			}
			set
			{
				__isset.@action = true;
				this._action = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @location;
			public bool @uid;
			public bool @action;
		}

		public ClientSelectOption()
		{
		}

		public ClientSelectOption DeepCopy()
		{
			var tmp20 = new ClientSelectOption()
			{
			};
			if(__isset.@location)
			{
				tmp20.Location = this.Location;
			}
			tmp20.__isset.@location = this.__isset.@location;
			if(__isset.@uid)
			{
				tmp20.Uid = this.Uid;
			}
			tmp20.__isset.@uid = this.__isset.@uid;
			if((Action != null) && __isset.@action)
			{
				tmp20.Action = this.Action.DeepCopy()!;
			}
			tmp20.__isset.@action = this.__isset.@action;
			return tmp20;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I32)
							{
								Location = (Constants.Location)await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.I32)
							{
								Uid = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 3:
							if(field.Type == TType.Struct)
							{
								Action = new CardAction();
								await Action.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp21 = new TStruct("ClientSelectOption");
				await oprot.WriteStructBeginAsync(tmp21, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp22 = new TField();
				if(__isset.@location)
				{
					tmp22.Name = "location";
					tmp22.Type = TType.I32;
					tmp22.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp22, cancellationToken);
					await oprot.WriteI32Async((int)Location, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.@uid)
				{
					tmp22.Name = "uid";
					tmp22.Type = TType.I32;
					tmp22.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp22, cancellationToken);
					await oprot.WriteI32Async(Uid, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Action != null) && __isset.@action)
				{
					tmp22.Name = "action";
					tmp22.Type = TType.Struct;
					tmp22.ID = 3;
					await oprot.WriteFieldBeginAsync(tmp22, cancellationToken);
					await Action.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientSelectOption other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@location == other.__isset.@location) && ((!__isset.@location) || (Equals(Location, other.Location))))
			  && ((__isset.@uid == other.__isset.@uid) && ((!__isset.@uid) || (Equals(Uid, other.Uid))))
			  && ((__isset.@action == other.__isset.@action) && ((!__isset.@action) || (Equals(Action, other.Action))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@location)
				{
					hashcode = (hashcode * 397) + Location.GetHashCode();
				}
				if(__isset.@uid)
				{
					hashcode = (hashcode * 397) + Uid.GetHashCode();
				}
				if((Action != null) && __isset.@action)
				{
					hashcode = (hashcode * 397) + Action.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp23 = new StringBuilder("ClientSelectOption(");
			int tmp24 = 0;
			if(__isset.@location)
			{
				if(0 < tmp24++) { _ = tmp23.Append(", "); }
				_ = tmp23.Append("Location: ");
				Location.ToString(tmp23);
			}
			if(__isset.@uid)
			{
				if(0 < tmp24++) { _ = tmp23.Append(", "); }
				_ = tmp23.Append("Uid: ");
				Uid.ToString(tmp23);
			}
			if((Action != null) && __isset.@action)
			{
				if(0 < tmp24++) { _ = tmp23.Append(", "); }
				_ = tmp23.Append("Action: ");
				Action.ToString(tmp23);
			}
			_ = tmp23.Append(')');
			return tmp23.ToString();
		}
	}

}
