/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class FieldCardInfo : TBase
	{
		private Constants.CardInfo? _info;

		public Constants.CardInfo? Info
		{
			get
			{
				return _info;
			}
			set
			{
				__isset.@info = true;
				this._info = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @info;
		}

		public FieldCardInfo()
		{
		}

		public FieldCardInfo DeepCopy()
		{
			var tmp141 = new FieldCardInfo()
			{
			};
			if((Info != null) && __isset.@info)
			{
				tmp141.Info = this.Info.DeepCopy()!;
			}
			tmp141.__isset.@info = this.__isset.@info;
			return tmp141;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Struct)
							{
								Info = new Constants.CardInfo();
								await Info.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp142 = new TStruct("FieldCardInfo");
				await oprot.WriteStructBeginAsync(tmp142, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp143 = new TField();
				if((Info != null) && __isset.@info)
				{
					tmp143.Name = "info";
					tmp143.Type = TType.Struct;
					tmp143.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp143, cancellationToken);
					await Info.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not FieldCardInfo other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@info == other.__isset.@info) && ((!__isset.@info) || (Equals(Info, other.Info))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Info != null) && __isset.@info)
				{
					hashcode = (hashcode * 397) + Info.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp144 = new StringBuilder("FieldCardInfo(");
			int tmp145 = 0;
			if((Info != null) && __isset.@info)
			{
				if(0 < tmp145++) { _ = tmp144.Append(", "); }
				_ = tmp144.Append("Info: ");
				Info.ToString(tmp144);
			}
			_ = tmp144.Append(')');
			return tmp144.ToString();
		}
	}

}
