/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class FieldUpdateField : TBase
	{
		private int _life;
		private int _deck_size;
		private int _grave_size;
		private int _momentum;
		private List<Constants.CardInfo>? _hand;
		private List<FieldCardInfo>? _field;
		private string? _name;
		private Constants.CardInfo? _ability;
		private Constants.CardInfo? _quest;
		private ShownInfo? _shown_info;

		public int Life
		{
			get
			{
				return _life;
			}
			set
			{
				__isset.@life = true;
				this._life = value;
			}
		}

		public int Deck_size
		{
			get
			{
				return _deck_size;
			}
			set
			{
				__isset.deck_size = true;
				this._deck_size = value;
			}
		}

		public int Grave_size
		{
			get
			{
				return _grave_size;
			}
			set
			{
				__isset.grave_size = true;
				this._grave_size = value;
			}
		}

		public int Momentum
		{
			get
			{
				return _momentum;
			}
			set
			{
				__isset.@momentum = true;
				this._momentum = value;
			}
		}

		public List<Constants.CardInfo>? Hand
		{
			get
			{
				return _hand;
			}
			set
			{
				__isset.@hand = true;
				this._hand = value;
			}
		}

		public List<FieldCardInfo>? Field
		{
			get
			{
				return _field;
			}
			set
			{
				__isset.@field = true;
				this._field = value;
			}
		}

		public string? Name
		{
			get
			{
				return _name;
			}
			set
			{
				__isset.@name = true;
				this._name = value;
			}
		}

		public Constants.CardInfo? Ability
		{
			get
			{
				return _ability;
			}
			set
			{
				__isset.@ability = true;
				this._ability = value;
			}
		}

		public Constants.CardInfo? Quest
		{
			get
			{
				return _quest;
			}
			set
			{
				__isset.@quest = true;
				this._quest = value;
			}
		}

		public ShownInfo? Shown_info
		{
			get
			{
				return _shown_info;
			}
			set
			{
				__isset.shown_info = true;
				this._shown_info = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @life;
			public bool deck_size;
			public bool grave_size;
			public bool @momentum;
			public bool @hand;
			public bool @field;
			public bool @name;
			public bool @ability;
			public bool @quest;
			public bool shown_info;
		}

		public FieldUpdateField()
		{
		}

		public FieldUpdateField DeepCopy()
		{
			var tmp128 = new FieldUpdateField()
			{
			};
			if(__isset.@life)
			{
				tmp128.Life = this.Life;
			}
			tmp128.__isset.@life = this.__isset.@life;
			if(__isset.deck_size)
			{
				tmp128.Deck_size = this.Deck_size;
			}
			tmp128.__isset.deck_size = this.__isset.deck_size;
			if(__isset.grave_size)
			{
				tmp128.Grave_size = this.Grave_size;
			}
			tmp128.__isset.grave_size = this.__isset.grave_size;
			if(__isset.@momentum)
			{
				tmp128.Momentum = this.Momentum;
			}
			tmp128.__isset.@momentum = this.__isset.@momentum;
			if((Hand != null) && __isset.@hand)
			{
				tmp128.Hand = this.Hand.DeepCopy()!;
			}
			tmp128.__isset.@hand = this.__isset.@hand;
			if((Field != null) && __isset.@field)
			{
				tmp128.Field = this.Field.DeepCopy()!;
			}
			tmp128.__isset.@field = this.__isset.@field;
			if((Name != null) && __isset.@name)
			{
				tmp128.Name = this.Name!;
			}
			tmp128.__isset.@name = this.__isset.@name;
			if((Ability != null) && __isset.@ability)
			{
				tmp128.Ability = this.Ability.DeepCopy()!;
			}
			tmp128.__isset.@ability = this.__isset.@ability;
			if((Quest != null) && __isset.@quest)
			{
				tmp128.Quest = this.Quest.DeepCopy()!;
			}
			tmp128.__isset.@quest = this.__isset.@quest;
			if((Shown_info != null) && __isset.shown_info)
			{
				tmp128.Shown_info = this.Shown_info.DeepCopy()!;
			}
			tmp128.__isset.shown_info = this.__isset.shown_info;
			return tmp128;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I32)
							{
								Life = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.I32)
							{
								Deck_size = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 3:
							if(field.Type == TType.I32)
							{
								Grave_size = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 4:
							if(field.Type == TType.I32)
							{
								Momentum = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 5:
							if(field.Type == TType.List)
							{
								{
									var _list129 = await iprot.ReadListBeginAsync(cancellationToken);
									Hand = new List<Constants.CardInfo>(_list129.Count);
									for(int _i130 = 0; _i130 < _list129.Count; ++_i130)
									{
										Constants.CardInfo _elem131;
										_elem131 = new Constants.CardInfo();
										await _elem131.ReadAsync(iprot, cancellationToken);
										Hand.Add(_elem131);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 6:
							if(field.Type == TType.List)
							{
								{
									var _list132 = await iprot.ReadListBeginAsync(cancellationToken);
									Field = new List<FieldCardInfo>(_list132.Count);
									for(int _i133 = 0; _i133 < _list132.Count; ++_i133)
									{
										FieldCardInfo _elem134;
										_elem134 = new FieldCardInfo();
										await _elem134.ReadAsync(iprot, cancellationToken);
										Field.Add(_elem134);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 7:
							if(field.Type == TType.String)
							{
								Name = await iprot.ReadStringAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 8:
							if(field.Type == TType.Struct)
							{
								Ability = new Constants.CardInfo();
								await Ability.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 9:
							if(field.Type == TType.Struct)
							{
								Quest = new Constants.CardInfo();
								await Quest.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 10:
							if(field.Type == TType.Struct)
							{
								Shown_info = new ShownInfo();
								await Shown_info.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp135 = new TStruct("FieldUpdateField");
				await oprot.WriteStructBeginAsync(tmp135, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp136 = new TField();
				if(__isset.@life)
				{
					tmp136.Name = "life";
					tmp136.Type = TType.I32;
					tmp136.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteI32Async(Life, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.deck_size)
				{
					tmp136.Name = "deck_size";
					tmp136.Type = TType.I32;
					tmp136.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteI32Async(Deck_size, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.grave_size)
				{
					tmp136.Name = "grave_size";
					tmp136.Type = TType.I32;
					tmp136.ID = 3;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteI32Async(Grave_size, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.@momentum)
				{
					tmp136.Name = "momentum";
					tmp136.Type = TType.I32;
					tmp136.ID = 4;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteI32Async(Momentum, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Hand != null) && __isset.@hand)
				{
					tmp136.Name = "hand";
					tmp136.Type = TType.List;
					tmp136.ID = 5;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.Struct, Hand.Count), cancellationToken);
					foreach(Constants.CardInfo _iter137 in Hand)
					{
						await _iter137.WriteAsync(oprot, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Field != null) && __isset.@field)
				{
					tmp136.Name = "field";
					tmp136.Type = TType.List;
					tmp136.ID = 6;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.Struct, Field.Count), cancellationToken);
					foreach(FieldCardInfo _iter138 in Field)
					{
						await _iter138.WriteAsync(oprot, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Name != null) && __isset.@name)
				{
					tmp136.Name = "name";
					tmp136.Type = TType.String;
					tmp136.ID = 7;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await oprot.WriteStringAsync(Name, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Ability != null) && __isset.@ability)
				{
					tmp136.Name = "ability";
					tmp136.Type = TType.Struct;
					tmp136.ID = 8;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await Ability.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Quest != null) && __isset.@quest)
				{
					tmp136.Name = "quest";
					tmp136.Type = TType.Struct;
					tmp136.ID = 9;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await Quest.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Shown_info != null) && __isset.shown_info)
				{
					tmp136.Name = "shown_info";
					tmp136.Type = TType.Struct;
					tmp136.ID = 10;
					await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
					await Shown_info.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not FieldUpdateField other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@life == other.__isset.@life) && ((!__isset.@life) || (Equals(Life, other.Life))))
			  && ((__isset.deck_size == other.__isset.deck_size) && ((!__isset.deck_size) || (Equals(Deck_size, other.Deck_size))))
			  && ((__isset.grave_size == other.__isset.grave_size) && ((!__isset.grave_size) || (Equals(Grave_size, other.Grave_size))))
			  && ((__isset.@momentum == other.__isset.@momentum) && ((!__isset.@momentum) || (Equals(Momentum, other.Momentum))))
			  && ((__isset.@hand == other.__isset.@hand) && ((!__isset.@hand) || (TCollections.Equals(Hand, other.Hand))))
			  && ((__isset.@field == other.__isset.@field) && ((!__isset.@field) || (TCollections.Equals(Field, other.Field))))
			  && ((__isset.@name == other.__isset.@name) && ((!__isset.@name) || (Equals(Name, other.Name))))
			  && ((__isset.@ability == other.__isset.@ability) && ((!__isset.@ability) || (Equals(Ability, other.Ability))))
			  && ((__isset.@quest == other.__isset.@quest) && ((!__isset.@quest) || (Equals(Quest, other.Quest))))
			  && ((__isset.shown_info == other.__isset.shown_info) && ((!__isset.shown_info) || (Equals(Shown_info, other.Shown_info))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@life)
				{
					hashcode = (hashcode * 397) + Life.GetHashCode();
				}
				if(__isset.deck_size)
				{
					hashcode = (hashcode * 397) + Deck_size.GetHashCode();
				}
				if(__isset.grave_size)
				{
					hashcode = (hashcode * 397) + Grave_size.GetHashCode();
				}
				if(__isset.@momentum)
				{
					hashcode = (hashcode * 397) + Momentum.GetHashCode();
				}
				if((Hand != null) && __isset.@hand)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Hand);
				}
				if((Field != null) && __isset.@field)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Field);
				}
				if((Name != null) && __isset.@name)
				{
					hashcode = (hashcode * 397) + Name.GetHashCode();
				}
				if((Ability != null) && __isset.@ability)
				{
					hashcode = (hashcode * 397) + Ability.GetHashCode();
				}
				if((Quest != null) && __isset.@quest)
				{
					hashcode = (hashcode * 397) + Quest.GetHashCode();
				}
				if((Shown_info != null) && __isset.shown_info)
				{
					hashcode = (hashcode * 397) + Shown_info.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp139 = new StringBuilder("FieldUpdateField(");
			int tmp140 = 0;
			if(__isset.@life)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Life: ");
				Life.ToString(tmp139);
			}
			if(__isset.deck_size)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Deck_size: ");
				Deck_size.ToString(tmp139);
			}
			if(__isset.grave_size)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Grave_size: ");
				Grave_size.ToString(tmp139);
			}
			if(__isset.@momentum)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Momentum: ");
				Momentum.ToString(tmp139);
			}
			if((Hand != null) && __isset.@hand)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Hand: ");
				Hand.ToString(tmp139);
			}
			if((Field != null) && __isset.@field)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Field: ");
				Field.ToString(tmp139);
			}
			if((Name != null) && __isset.@name)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Name: ");
				Name.ToString(tmp139);
			}
			if((Ability != null) && __isset.@ability)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Ability: ");
				Ability.ToString(tmp139);
			}
			if((Quest != null) && __isset.@quest)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Quest: ");
				Quest.ToString(tmp139);
			}
			if((Shown_info != null) && __isset.shown_info)
			{
				if(0 < tmp140++) { _ = tmp139.Append(", "); }
				_ = tmp139.Append("Shown_info: ");
				Shown_info.ToString(tmp139);
			}
			_ = tmp139.Append(')');
			return tmp139.ToString();
		}
	}

}
