/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{
	public abstract partial class ReplayPacket : TUnionBase
	{
		public abstract Task WriteAsync(TProtocol tProtocol, CancellationToken cancellationToken);
		public readonly int Isset;
		public abstract object? Data { get; }
		protected ReplayPacket(int isset)
		{
			Isset = isset;
		}

		public override bool Equals(object? that)
		{
			if(that is not ReplayPacket other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			if(this.Isset != other.Isset)
			{
				return false;
			}

			return Isset switch
			{
				1 => Equals(As_client, other.As_client),
				2 => Equals(As_server, other.As_server),
				_ => true,
			};
		}

		public override int GetHashCode()
		{
			return Isset switch
			{
				1 => As_client?.GetHashCode() ?? 0,
				2 => As_server?.GetHashCode() ?? 0,
				_ => (new ___undefined()).GetHashCode()
			};
		}

		public ReplayPacket DeepCopy()
		{
			return Isset switch
			{
				1 => new client(As_client?.DeepCopy() ?? new ClientPacket.___undefined()),
				2 => new server(As_server?.DeepCopy() ?? new ServerPacket.___undefined()),
				_ => new ___undefined()
			};
		}

		public class ___undefined : ReplayPacket
		{
			public override object? Data { get { return null; } }
			public ___undefined() : base(0) { }

			public new ___undefined DeepCopy()
			{
				return new ___undefined();
			}

			public override bool Equals(object? that)
			{
				if(that is not ___undefined other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return true;
			}

			public override int GetHashCode()
			{
				int hashcode = 157;
				unchecked
				{
				}
				return hashcode;
			}

			public override Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				throw new TProtocolException(TProtocolException.INVALID_DATA, "Cannot persist an union type which is not set.");
			}

		}

		public ClientPacket? As_client
		{
			get
			{
				return (1 == Isset) && (Data != null) ? (ClientPacket?)Data : default;
			}
		}

		public class @client : ReplayPacket
		{
			private readonly ClientPacket _data;
			public override object? Data { get { return _data; } }
			public @client(ClientPacket data) : base(1)
			{
				this._data = data;
			}
			public new @client DeepCopy()
			{
				return new @client(_data.DeepCopy()!);
			}

			public override bool Equals(object? that)
			{
				if(that is not ReplayPacket other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return Equals(_data, other.As_client);
			}

			public override int GetHashCode()
			{
				return _data.GetHashCode();
			}

			public override async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				oprot.IncrementRecursionDepth();
				try
				{
					var struc = new TStruct("ReplayPacket");
					await oprot.WriteStructBeginAsync(struc, cancellationToken);
					var field = new TField()
					{
						Name = "client",
						Type = TType.Struct,
						ID = 1
					};
					await oprot.WriteFieldBeginAsync(field, cancellationToken);
					await _data.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
					await oprot.WriteFieldStopAsync(cancellationToken);
					await oprot.WriteStructEndAsync(cancellationToken);
				}
				finally
				{
					oprot.DecrementRecursionDepth();
				}
			}
		}

		public ServerPacket? As_server
		{
			get
			{
				return (2 == Isset) && (Data != null) ? (ServerPacket?)Data : default;
			}
		}

		public class @server : ReplayPacket
		{
			private readonly ServerPacket _data;
			public override object? Data { get { return _data; } }
			public @server(ServerPacket data) : base(2)
			{
				this._data = data;
			}
			public new @server DeepCopy()
			{
				return new @server(_data.DeepCopy()!);
			}

			public override bool Equals(object? that)
			{
				if(that is not ReplayPacket other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return Equals(_data, other.As_server);
			}

			public override int GetHashCode()
			{
				return _data.GetHashCode();
			}

			public override async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				oprot.IncrementRecursionDepth();
				try
				{
					var struc = new TStruct("ReplayPacket");
					await oprot.WriteStructBeginAsync(struc, cancellationToken);
					var field = new TField()
					{
						Name = "server",
						Type = TType.Struct,
						ID = 2
					};
					await oprot.WriteFieldBeginAsync(field, cancellationToken);
					await _data.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
					await oprot.WriteFieldStopAsync(cancellationToken);
					await oprot.WriteStructEndAsync(cancellationToken);
				}
				finally
				{
					oprot.DecrementRecursionDepth();
				}
			}
		}

		public static async Task<ReplayPacket> ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				ReplayPacket tmp192;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				TField field = await iprot.ReadFieldBeginAsync(cancellationToken);
				if(field.Type == TType.Stop)
				{
					await iprot.ReadFieldEndAsync(cancellationToken);
					tmp192 = new ___undefined();
				}
				else
				{
					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Struct)
							{
								ClientPacket tmp193;
								tmp193 = await ClientPacket.ReadAsync(iprot, cancellationToken);
								tmp192 = new client(tmp193);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
								tmp192 = new ___undefined();
							}
							break;
						case 2:
							if(field.Type == TType.Struct)
							{
								ServerPacket tmp194;
								tmp194 = await ServerPacket.ReadAsync(iprot, cancellationToken);
								tmp192 = new server(tmp194);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
								tmp192 = new ___undefined();
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							tmp192 = new ___undefined();
							break;
					}
					await iprot.ReadFieldEndAsync(cancellationToken);
					if((await iprot.ReadFieldBeginAsync(cancellationToken)).Type != TType.Stop)
					{
						throw new TProtocolException(TProtocolException.INVALID_DATA);
					}
				}
				await iprot.ReadStructEndAsync(cancellationToken);
				return tmp192;
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

	}

}
