/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ServerSelectZone : TBase
	{
		private List<bool>? _possibilities;

		public List<bool>? Possibilities
		{
			get
			{
				return _possibilities;
			}
			set
			{
				__isset.@possibilities = true;
				this._possibilities = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @possibilities;
		}

		public ServerSelectZone()
		{
		}

		public ServerSelectZone DeepCopy()
		{
			var tmp160 = new ServerSelectZone()
			{
			};
			if((Possibilities != null) && __isset.@possibilities)
			{
				tmp160.Possibilities = this.Possibilities.DeepCopy()!;
			}
			tmp160.__isset.@possibilities = this.__isset.@possibilities;
			return tmp160;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.List)
							{
								{
									var _list161 = await iprot.ReadListBeginAsync(cancellationToken);
									Possibilities = new List<bool>(_list161.Count);
									for(int _i162 = 0; _i162 < _list161.Count; ++_i162)
									{
										bool _elem163;
										_elem163 = await iprot.ReadBoolAsync(cancellationToken);
										Possibilities.Add(_elem163);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp164 = new TStruct("ServerSelectZone");
				await oprot.WriteStructBeginAsync(tmp164, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp165 = new TField();
				if((Possibilities != null) && __isset.@possibilities)
				{
					tmp165.Name = "possibilities";
					tmp165.Type = TType.List;
					tmp165.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp165, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.Bool, Possibilities.Count), cancellationToken);
					foreach(bool _iter166 in Possibilities)
					{
						await oprot.WriteBoolAsync(_iter166, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerSelectZone other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@possibilities == other.__isset.@possibilities) && ((!__isset.@possibilities) || (TCollections.Equals(Possibilities, other.Possibilities))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Possibilities != null) && __isset.@possibilities)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Possibilities);
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp167 = new StringBuilder("ServerSelectZone(");
			int tmp168 = 0;
			if((Possibilities != null) && __isset.@possibilities)
			{
				if(0 < tmp168++) { _ = tmp167.Append(", "); }
				_ = tmp167.Append("Possibilities: ");
				Possibilities.ToString(tmp167);
			}
			_ = tmp167.Append(')');
			return tmp167.ToString();
		}
	}

}
