/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ServerGetOptions : TBase
	{
		private Constants.Location _location;
		private int _uid;
		private List<CardAction>? _options;

		/// <summary>
		/// 
		/// <seealso cref="Constants.Location"/>
		/// </summary>
		public Constants.Location Location
		{
			get
			{
				return _location;
			}
			set
			{
				__isset.@location = true;
				this._location = value;
			}
		}

		public int Uid
		{
			get
			{
				return _uid;
			}
			set
			{
				__isset.@uid = true;
				this._uid = value;
			}
		}

		public List<CardAction>? Options
		{
			get
			{
				return _options;
			}
			set
			{
				__isset.@options = true;
				this._options = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @location;
			public bool @uid;
			public bool @options;
		}

		public ServerGetOptions()
		{
		}

		public ServerGetOptions DeepCopy()
		{
			var tmp86 = new ServerGetOptions()
			{
			};
			if(__isset.@location)
			{
				tmp86.Location = this.Location;
			}
			tmp86.__isset.@location = this.__isset.@location;
			if(__isset.@uid)
			{
				tmp86.Uid = this.Uid;
			}
			tmp86.__isset.@uid = this.__isset.@uid;
			if((Options != null) && __isset.@options)
			{
				tmp86.Options = this.Options.DeepCopy()!;
			}
			tmp86.__isset.@options = this.__isset.@options;
			return tmp86;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I32)
							{
								Location = (Constants.Location)await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.I32)
							{
								Uid = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 3:
							if(field.Type == TType.List)
							{
								{
									var _list87 = await iprot.ReadListBeginAsync(cancellationToken);
									Options = new List<CardAction>(_list87.Count);
									for(int _i88 = 0; _i88 < _list87.Count; ++_i88)
									{
										CardAction _elem89;
										_elem89 = new CardAction();
										await _elem89.ReadAsync(iprot, cancellationToken);
										Options.Add(_elem89);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp90 = new TStruct("ServerGetOptions");
				await oprot.WriteStructBeginAsync(tmp90, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp91 = new TField();
				if(__isset.@location)
				{
					tmp91.Name = "location";
					tmp91.Type = TType.I32;
					tmp91.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp91, cancellationToken);
					await oprot.WriteI32Async((int)Location, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.@uid)
				{
					tmp91.Name = "uid";
					tmp91.Type = TType.I32;
					tmp91.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp91, cancellationToken);
					await oprot.WriteI32Async(Uid, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Options != null) && __isset.@options)
				{
					tmp91.Name = "options";
					tmp91.Type = TType.List;
					tmp91.ID = 3;
					await oprot.WriteFieldBeginAsync(tmp91, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.Struct, Options.Count), cancellationToken);
					foreach(CardAction _iter92 in Options)
					{
						await _iter92.WriteAsync(oprot, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerGetOptions other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@location == other.__isset.@location) && ((!__isset.@location) || (Equals(Location, other.Location))))
			  && ((__isset.@uid == other.__isset.@uid) && ((!__isset.@uid) || (Equals(Uid, other.Uid))))
			  && ((__isset.@options == other.__isset.@options) && ((!__isset.@options) || (TCollections.Equals(Options, other.Options))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@location)
				{
					hashcode = (hashcode * 397) + Location.GetHashCode();
				}
				if(__isset.@uid)
				{
					hashcode = (hashcode * 397) + Uid.GetHashCode();
				}
				if((Options != null) && __isset.@options)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Options);
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp93 = new StringBuilder("ServerGetOptions(");
			int tmp94 = 0;
			if(__isset.@location)
			{
				if(0 < tmp94++) { _ = tmp93.Append(", "); }
				_ = tmp93.Append("Location: ");
				Location.ToString(tmp93);
			}
			if(__isset.@uid)
			{
				if(0 < tmp94++) { _ = tmp93.Append(", "); }
				_ = tmp93.Append("Uid: ");
				Uid.ToString(tmp93);
			}
			if((Options != null) && __isset.@options)
			{
				if(0 < tmp94++) { _ = tmp93.Append(", "); }
				_ = tmp93.Append("Options: ");
				Options.ToString(tmp93);
			}
			_ = tmp93.Append(')');
			return tmp93.ToString();
		}
	}

}
