/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Duel
{

	public partial class ShownInfo : TBase
	{
		private Constants.CardInfo? _card;
		private string? _description;

		public Constants.CardInfo? Card
		{
			get
			{
				return _card;
			}
			set
			{
				__isset.@card = true;
				this._card = value;
			}
		}

		public string? Description
		{
			get
			{
				return _description;
			}
			set
			{
				__isset.@description = true;
				this._description = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @card;
			public bool @description;
		}

		public ShownInfo()
		{
		}

		public ShownInfo DeepCopy()
		{
			var tmp146 = new ShownInfo()
			{
			};
			if((Card != null) && __isset.@card)
			{
				tmp146.Card = this.Card.DeepCopy()!;
			}
			tmp146.__isset.@card = this.__isset.@card;
			if((Description != null) && __isset.@description)
			{
				tmp146.Description = this.Description!;
			}
			tmp146.__isset.@description = this.__isset.@description;
			return tmp146;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Struct)
							{
								Card = new Constants.CardInfo();
								await Card.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.String)
							{
								Description = await iprot.ReadStringAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp147 = new TStruct("ShownInfo");
				await oprot.WriteStructBeginAsync(tmp147, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp148 = new TField();
				if((Card != null) && __isset.@card)
				{
					tmp148.Name = "card";
					tmp148.Type = TType.Struct;
					tmp148.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp148, cancellationToken);
					await Card.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Description != null) && __isset.@description)
				{
					tmp148.Name = "description";
					tmp148.Type = TType.String;
					tmp148.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp148, cancellationToken);
					await oprot.WriteStringAsync(Description, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ShownInfo other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@card == other.__isset.@card) && ((!__isset.@card) || (Equals(Card, other.Card))))
			  && ((__isset.@description == other.__isset.@description) && ((!__isset.@description) || (Equals(Description, other.Description))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Card != null) && __isset.@card)
				{
					hashcode = (hashcode * 397) + Card.GetHashCode();
				}
				if((Description != null) && __isset.@description)
				{
					hashcode = (hashcode * 397) + Description.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp149 = new StringBuilder("ShownInfo(");
			int tmp150 = 0;
			if((Card != null) && __isset.@card)
			{
				if(0 < tmp150++) { _ = tmp149.Append(", "); }
				_ = tmp149.Append("Card: ");
				Card.ToString(tmp149);
			}
			if((Description != null) && __isset.@description)
			{
				if(0 < tmp150++) { _ = tmp149.Append(", "); }
				_ = tmp149.Append("Description: ");
				Description.ToString(tmp149);
			}
			_ = tmp149.Append(')');
			return tmp149.ToString();
		}
	}

}
