/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Deck
{

	public partial class ClientUpdateList : TBase
	{
		private DeckInfo? _deck;

		public DeckInfo? Deck
		{
			get
			{
				return _deck;
			}
			set
			{
				__isset.@deck = true;
				this._deck = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @deck;
		}

		public ClientUpdateList()
		{
		}

		public ClientUpdateList DeepCopy()
		{
			var tmp20 = new ClientUpdateList()
			{
			};
			if((Deck != null) && __isset.@deck)
			{
				tmp20.Deck = this.Deck.DeepCopy()!;
			}
			tmp20.__isset.@deck = this.__isset.@deck;
			return tmp20;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Struct)
							{
								Deck = new DeckInfo();
								await Deck.ReadAsync(iprot, cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp21 = new TStruct("ClientUpdateList");
				await oprot.WriteStructBeginAsync(tmp21, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp22 = new TField();
				if((Deck != null) && __isset.@deck)
				{
					tmp22.Name = "deck";
					tmp22.Type = TType.Struct;
					tmp22.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp22, cancellationToken);
					await Deck.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientUpdateList other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@deck == other.__isset.@deck) && ((!__isset.@deck) || (Equals(Deck, other.Deck))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Deck != null) && __isset.@deck)
				{
					hashcode = (hashcode * 397) + Deck.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp23 = new StringBuilder("ClientUpdateList(");
			int tmp24 = 0;
			if((Deck != null) && __isset.@deck)
			{
				if(0 < tmp24++) { _ = tmp23.Append(", "); }
				_ = tmp23.Append("Deck: ");
				Deck.ToString(tmp23);
			}
			_ = tmp23.Append(')');
			return tmp23.ToString();
		}
	}

}
