/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using Thrift.Collections;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Deck
{
	public static class DeckPacketsExtensions
	{
		public static bool Equals(this List<Constants.CardInfo> instance, object that)
		{
			if(that is not List<Constants.CardInfo> other)
			{
				return false;
			}

			if(ReferenceEquals(instance, other))
			{
				return true;
			}

			return TCollections.Equals(instance, other);
		}


		public static int GetHashCode(this List<Constants.CardInfo> instance)
		{
			return TCollections.GetHashCode(instance);
		}


		public static List<Constants.CardInfo>? DeepCopy(this List<Constants.CardInfo>? source)
		{
			if(source == null)
			{
				return null;
			}

			var tmp66 = new List<Constants.CardInfo>(source.Count);
			foreach(var elem in source)
			{
				tmp66.Add(elem.DeepCopy()!);
			}

			return tmp66;
		}


		public static bool Equals(this List<string> instance, object that)
		{
			if(that is not List<string> other)
			{
				return false;
			}

			if(ReferenceEquals(instance, other))
			{
				return true;
			}

			return TCollections.Equals(instance, other);
		}


		public static int GetHashCode(this List<string> instance)
		{
			return TCollections.GetHashCode(instance);
		}


		public static List<string>? DeepCopy(this List<string>? source)
		{
			if(source == null)
			{
				return null;
			}

			var tmp67 = new List<string>(source.Count);
			foreach(var elem in source)
			{
				tmp67.Add(elem!);
			}

			return tmp67;
		}


	}
}
