/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Deck
{

	public partial class ServerNames : TBase
	{
		private List<string>? _names;

		public List<string>? Names
		{
			get
			{
				return _names;
			}
			set
			{
				__isset.@names = true;
				this._names = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @names;
		}

		public ServerNames()
		{
		}

		public ServerNames DeepCopy()
		{
			var tmp34 = new ServerNames()
			{
			};
			if((Names != null) && __isset.@names)
			{
				tmp34.Names = this.Names.DeepCopy()!;
			}
			tmp34.__isset.@names = this.__isset.@names;
			return tmp34;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.List)
							{
								{
									var _list35 = await iprot.ReadListBeginAsync(cancellationToken);
									Names = new List<string>(_list35.Count);
									for(int _i36 = 0; _i36 < _list35.Count; ++_i36)
									{
										string _elem37;
										_elem37 = await iprot.ReadStringAsync(cancellationToken);
										Names.Add(_elem37);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp38 = new TStruct("ServerNames");
				await oprot.WriteStructBeginAsync(tmp38, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp39 = new TField();
				if((Names != null) && __isset.@names)
				{
					tmp39.Name = "names";
					tmp39.Type = TType.List;
					tmp39.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp39, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.String, Names.Count), cancellationToken);
					foreach(string _iter40 in Names)
					{
						await oprot.WriteStringAsync(_iter40, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerNames other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@names == other.__isset.@names) && ((!__isset.@names) || (TCollections.Equals(Names, other.Names))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Names != null) && __isset.@names)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Names);
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp41 = new StringBuilder("ServerNames(");
			int tmp42 = 0;
			if((Names != null) && __isset.@names)
			{
				if(0 < tmp42++) { _ = tmp41.Append(", "); }
				_ = tmp41.Append("Names: ");
				Names.ToString(tmp41);
			}
			_ = tmp41.Append(')');
			return tmp41.ToString();
		}
	}

}
