/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Deck
{
	public abstract partial class ServerPacketContent : TUnionBase
	{
		public abstract Task WriteAsync(TProtocol tProtocol, CancellationToken cancellationToken);
		public readonly int Isset;
		public abstract object? Data { get; }
		protected ServerPacketContent(int isset)
		{
			Isset = isset;
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerPacketContent other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			if(this.Isset != other.Isset)
			{
				return false;
			}

			return Isset switch
			{
				1 => Equals(As_names, other.As_names),
				2 => Equals(As_list, other.As_list),
				3 => Equals(As_search, other.As_search),
				_ => true,
			};
		}

		public override int GetHashCode()
		{
			return Isset switch
			{
				1 => As_names?.GetHashCode() ?? 0,
				2 => As_list?.GetHashCode() ?? 0,
				3 => As_search?.GetHashCode() ?? 0,
				_ => (new ___undefined()).GetHashCode()
			};
		}

		public ServerPacketContent DeepCopy()
		{
			return Isset switch
			{
				1 => new names(As_names?.DeepCopy() ?? new()),
				2 => new list(As_list?.DeepCopy() ?? new()),
				3 => new search(As_search?.DeepCopy() ?? new()),
				_ => new ___undefined()
			};
		}

		public class ___undefined : ServerPacketContent
		{
			public override object? Data { get { return null; } }
			public ___undefined() : base(0) { }

			public new ___undefined DeepCopy()
			{
				return new ___undefined();
			}

			public override bool Equals(object? that)
			{
				if(that is not ___undefined other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return true;
			}

			public override int GetHashCode()
			{
				int hashcode = 157;
				unchecked
				{
				}
				return hashcode;
			}

			public override Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				throw new TProtocolException(TProtocolException.INVALID_DATA, "Cannot persist an union type which is not set.");
			}

		}

		public ServerNames? As_names
		{
			get
			{
				return (1 == Isset) && (Data != null) ? (ServerNames?)Data : default;
			}
		}

		public class @names : ServerPacketContent
		{
			private readonly ServerNames _data;
			public override object? Data { get { return _data; } }
			public @names(ServerNames data) : base(1)
			{
				this._data = data;
			}
			public new @names DeepCopy()
			{
				return new @names(_data.DeepCopy()!);
			}

			public override bool Equals(object? that)
			{
				if(that is not ServerPacketContent other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return Equals(_data, other.As_names);
			}

			public override int GetHashCode()
			{
				return _data.GetHashCode();
			}

			public override async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				oprot.IncrementRecursionDepth();
				try
				{
					var struc = new TStruct("ServerPacketContent");
					await oprot.WriteStructBeginAsync(struc, cancellationToken);
					var field = new TField()
					{
						Name = "names",
						Type = TType.Struct,
						ID = 1
					};
					await oprot.WriteFieldBeginAsync(field, cancellationToken);
					await _data.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
					await oprot.WriteFieldStopAsync(cancellationToken);
					await oprot.WriteStructEndAsync(cancellationToken);
				}
				finally
				{
					oprot.DecrementRecursionDepth();
				}
			}
		}

		public ServerList? As_list
		{
			get
			{
				return (2 == Isset) && (Data != null) ? (ServerList?)Data : default;
			}
		}

		public class @list : ServerPacketContent
		{
			private readonly ServerList _data;
			public override object? Data { get { return _data; } }
			public @list(ServerList data) : base(2)
			{
				this._data = data;
			}
			public new @list DeepCopy()
			{
				return new @list(_data.DeepCopy()!);
			}

			public override bool Equals(object? that)
			{
				if(that is not ServerPacketContent other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return Equals(_data, other.As_list);
			}

			public override int GetHashCode()
			{
				return _data.GetHashCode();
			}

			public override async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				oprot.IncrementRecursionDepth();
				try
				{
					var struc = new TStruct("ServerPacketContent");
					await oprot.WriteStructBeginAsync(struc, cancellationToken);
					var field = new TField()
					{
						Name = "list",
						Type = TType.Struct,
						ID = 2
					};
					await oprot.WriteFieldBeginAsync(field, cancellationToken);
					await _data.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
					await oprot.WriteFieldStopAsync(cancellationToken);
					await oprot.WriteStructEndAsync(cancellationToken);
				}
				finally
				{
					oprot.DecrementRecursionDepth();
				}
			}
		}

		public ServerSearch? As_search
		{
			get
			{
				return (3 == Isset) && (Data != null) ? (ServerSearch?)Data : default;
			}
		}

		public class @search : ServerPacketContent
		{
			private readonly ServerSearch _data;
			public override object? Data { get { return _data; } }
			public @search(ServerSearch data) : base(3)
			{
				this._data = data;
			}
			public new @search DeepCopy()
			{
				return new @search(_data.DeepCopy()!);
			}

			public override bool Equals(object? that)
			{
				if(that is not ServerPacketContent other)
				{
					return false;
				}

				if(ReferenceEquals(this, other))
				{
					return true;
				}

				return Equals(_data, other.As_search);
			}

			public override int GetHashCode()
			{
				return _data.GetHashCode();
			}

			public override async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
			{
				oprot.IncrementRecursionDepth();
				try
				{
					var struc = new TStruct("ServerPacketContent");
					await oprot.WriteStructBeginAsync(struc, cancellationToken);
					var field = new TField()
					{
						Name = "search",
						Type = TType.Struct,
						ID = 3
					};
					await oprot.WriteFieldBeginAsync(field, cancellationToken);
					await _data.WriteAsync(oprot, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
					await oprot.WriteFieldStopAsync(cancellationToken);
					await oprot.WriteStructEndAsync(cancellationToken);
				}
				finally
				{
					oprot.DecrementRecursionDepth();
				}
			}
		}

		public static async Task<ServerPacketContent> ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				ServerPacketContent tmp40;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				TField field = await iprot.ReadFieldBeginAsync(cancellationToken);
				if(field.Type == TType.Stop)
				{
					await iprot.ReadFieldEndAsync(cancellationToken);
					tmp40 = new ___undefined();
				}
				else
				{
					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.Struct)
							{
								ServerNames tmp41;
								tmp41 = new ServerNames();
								await tmp41.ReadAsync(iprot, cancellationToken);
								tmp40 = new names(tmp41);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
								tmp40 = new ___undefined();
							}
							break;
						case 2:
							if(field.Type == TType.Struct)
							{
								ServerList tmp42;
								tmp42 = new ServerList();
								await tmp42.ReadAsync(iprot, cancellationToken);
								tmp40 = new list(tmp42);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
								tmp40 = new ___undefined();
							}
							break;
						case 3:
							if(field.Type == TType.Struct)
							{
								ServerSearch tmp43;
								tmp43 = new ServerSearch();
								await tmp43.ReadAsync(iprot, cancellationToken);
								tmp40 = new search(tmp43);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
								tmp40 = new ___undefined();
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							tmp40 = new ___undefined();
							break;
					}
					await iprot.ReadFieldEndAsync(cancellationToken);
					if((await iprot.ReadFieldBeginAsync(cancellationToken)).Type != TType.Stop)
					{
						throw new TProtocolException(TProtocolException.INVALID_DATA);
					}
				}
				await iprot.ReadStructEndAsync(cancellationToken);
				return tmp40;
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

	}

}
