// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

public enum ArtworkFiletype : byte
{
  UNKNOWN = 0,
  JPG = 1,
  PNG = 2,
};


}
