// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientCreatePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientCreatePacket GetRootAsClientCreatePacket(ByteBuffer _bb) { return GetRootAsClientCreatePacket(_bb, new ClientCreatePacket()); }
  public static ClientCreatePacket GetRootAsClientCreatePacket(ByteBuffer _bb, ClientCreatePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientCreatePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<CardGameUtils.Packets.Server.ClientCreatePacket> CreateClientCreatePacket(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    ClientCreatePacket.AddName(builder, nameOffset);
    return ClientCreatePacket.EndClientCreatePacket(builder);
  }

  public static void StartClientCreatePacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Server.ClientCreatePacket> EndClientCreatePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ClientCreatePacket>(o);
  }
  public ClientCreatePacketT UnPack() {
    var _o = new ClientCreatePacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientCreatePacketT _o) {
    _o.Name = this.Name;
  }
  public static Offset<CardGameUtils.Packets.Server.ClientCreatePacket> Pack(FlatBufferBuilder builder, ClientCreatePacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ClientCreatePacket>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateClientCreatePacket(
      builder,
      _name);
  }
}

public class ClientCreatePacketT
{
  public string Name { get; set; }

  public ClientCreatePacketT() {
    this.Name = null;
  }
}


static public class ClientCreatePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
