// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientJoinPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientJoinPacket GetRootAsClientJoinPacket(ByteBuffer _bb) { return GetRootAsClientJoinPacket(_bb, new ClientJoinPacket()); }
  public static ClientJoinPacket GetRootAsClientJoinPacket(ByteBuffer _bb, ClientJoinPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientJoinPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string OwnName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetOwnNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetOwnNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetOwnNameArray() { return __p.__vector_as_array<byte>(4); }
  public string OppName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetOppNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetOppNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetOppNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<CardGameUtils.Packets.Server.ClientJoinPacket> CreateClientJoinPacket(FlatBufferBuilder builder,
      StringOffset own_nameOffset = default(StringOffset),
      StringOffset opp_nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    ClientJoinPacket.AddOppName(builder, opp_nameOffset);
    ClientJoinPacket.AddOwnName(builder, own_nameOffset);
    return ClientJoinPacket.EndClientJoinPacket(builder);
  }

  public static void StartClientJoinPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddOwnName(FlatBufferBuilder builder, StringOffset ownNameOffset) { builder.AddOffset(0, ownNameOffset.Value, 0); }
  public static void AddOppName(FlatBufferBuilder builder, StringOffset oppNameOffset) { builder.AddOffset(1, oppNameOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Server.ClientJoinPacket> EndClientJoinPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ClientJoinPacket>(o);
  }
  public ClientJoinPacketT UnPack() {
    var _o = new ClientJoinPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientJoinPacketT _o) {
    _o.OwnName = this.OwnName;
    _o.OppName = this.OppName;
  }
  public static Offset<CardGameUtils.Packets.Server.ClientJoinPacket> Pack(FlatBufferBuilder builder, ClientJoinPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ClientJoinPacket>);
    var _own_name = _o.OwnName == null ? default(StringOffset) : builder.CreateString(_o.OwnName);
    var _opp_name = _o.OppName == null ? default(StringOffset) : builder.CreateString(_o.OppName);
    return CreateClientJoinPacket(
      builder,
      _own_name,
      _opp_name);
  }
}

public class ClientJoinPacketT
{
  public string OwnName { get; set; }
  public string OppName { get; set; }

  public ClientJoinPacketT() {
    this.OwnName = null;
    this.OppName = null;
  }
}


static public class ClientJoinPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*OwnName*/, false)
      && verifier.VerifyString(tablePos, 6 /*OppName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
