// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientPacket GetRootAsClientPacket(ByteBuffer _bb) { return GetRootAsClientPacket(_bb, new ClientPacket()); }
  public static ClientPacket GetRootAsClientPacket(ByteBuffer _bb, ClientPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ClientPacketBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "srvr"); }
  public static bool VerifyClientPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("srvr", false, ClientPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Packets.Server.ClientContent ContentType { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Packets.Server.ClientContent)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Packets.Server.ClientContent.NONE; } }
  public TTable? Content<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public CardGameUtils.Packets.Server.ClientAdditionalCardsPacket ContentAsadditional_cards() { return Content<CardGameUtils.Packets.Server.ClientAdditionalCardsPacket>().Value; }
  public CardGameUtils.Packets.Server.ClientArtworksPacket ContentAsartworks() { return Content<CardGameUtils.Packets.Server.ClientArtworksPacket>().Value; }
  public CardGameUtils.Packets.Server.ClientCreatePacket ContentAscreate() { return Content<CardGameUtils.Packets.Server.ClientCreatePacket>().Value; }
  public CardGameUtils.Packets.Server.ClientJoinPacket ContentAsjoin() { return Content<CardGameUtils.Packets.Server.ClientJoinPacket>().Value; }
  public CardGameUtils.Packets.Server.ClientLeavePacket ContentAsleave() { return Content<CardGameUtils.Packets.Server.ClientLeavePacket>().Value; }
  public CardGameUtils.Packets.Server.ClientRoomsPacket ContentAsrooms() { return Content<CardGameUtils.Packets.Server.ClientRoomsPacket>().Value; }
  public CardGameUtils.Packets.Server.ClientStartPacket ContentAsstart() { return Content<CardGameUtils.Packets.Server.ClientStartPacket>().Value; }

  public static Offset<CardGameUtils.Packets.Server.ClientPacket> CreateClientPacket(FlatBufferBuilder builder,
      CardGameUtils.Packets.Server.ClientContent content_type = CardGameUtils.Packets.Server.ClientContent.NONE,
      int contentOffset = 0) {
    builder.StartTable(2);
    ClientPacket.AddContent(builder, contentOffset);
    ClientPacket.AddContentType(builder, content_type);
    return ClientPacket.EndClientPacket(builder);
  }

  public static void StartClientPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddContentType(FlatBufferBuilder builder, CardGameUtils.Packets.Server.ClientContent contentType) { builder.AddByte(0, (byte)contentType, 0); }
  public static void AddContent(FlatBufferBuilder builder, int contentOffset) { builder.AddOffset(1, contentOffset, 0); }
  public static Offset<CardGameUtils.Packets.Server.ClientPacket> EndClientPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ClientPacket>(o);
  }
  public static void FinishClientPacketBuffer(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Server.ClientPacket> offset) { builder.Finish(offset.Value, "srvr"); }
  public static void FinishSizePrefixedClientPacketBuffer(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Server.ClientPacket> offset) { builder.FinishSizePrefixed(offset.Value, "srvr"); }
  public ClientPacketT UnPack() {
    var _o = new ClientPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientPacketT _o) {
    _o.Content = new CardGameUtils.Packets.Server.ClientContentUnion();
    _o.Content.Type = this.ContentType;
    switch (this.ContentType) {
      default: break;
      case CardGameUtils.Packets.Server.ClientContent.additional_cards:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientAdditionalCardsPacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientAdditionalCardsPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.artworks:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientArtworksPacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientArtworksPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.create:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientCreatePacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientCreatePacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.join:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientJoinPacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientJoinPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.leave:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientLeavePacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientLeavePacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.rooms:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientRoomsPacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientRoomsPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ClientContent.start:
        _o.Content.Value = this.Content<CardGameUtils.Packets.Server.ClientStartPacket>().HasValue ? this.Content<CardGameUtils.Packets.Server.ClientStartPacket>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<CardGameUtils.Packets.Server.ClientPacket> Pack(FlatBufferBuilder builder, ClientPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ClientPacket>);
    var _content_type = _o.Content == null ? CardGameUtils.Packets.Server.ClientContent.NONE : _o.Content.Type;
    var _content = _o.Content == null ? 0 : CardGameUtils.Packets.Server.ClientContentUnion.Pack(builder, _o.Content);
    return CreateClientPacket(
      builder,
      _content_type,
      _content);
  }
}

public class ClientPacketT
{
  public CardGameUtils.Packets.Server.ClientContentUnion Content { get; set; }

  public ClientPacketT() {
    this.Content = null;
  }
  public static ClientPacketT DeserializeFromBinary(byte[] fbBuffer) {
    return ClientPacket.GetRootAsClientPacket(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ClientPacket.FinishClientPacketBuffer(fbb, ClientPacket.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class ClientPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ContentType*/, 1 /*CardGameUtils.Packets.Server.ClientContent*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Content*/, CardGameUtils.Packets.Server.ClientContentVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
