// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResultSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ResultSuccess GetRootAsResultSuccess(ByteBuffer _bb) { return GetRootAsResultSuccess(_bb, new ResultSuccess()); }
  public static ResultSuccess GetRootAsResultSuccess(ByteBuffer _bb, ResultSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResultSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartResultSuccess(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<CardGameUtils.Packets.Server.ResultSuccess> EndResultSuccess(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ResultSuccess>(o);
  }
  public ResultSuccessT UnPack() {
    var _o = new ResultSuccessT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResultSuccessT _o) {
  }
  public static Offset<CardGameUtils.Packets.Server.ResultSuccess> Pack(FlatBufferBuilder builder, ResultSuccessT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ResultSuccess>);
    StartResultSuccess(builder);
    return EndResultSuccess(builder);
  }
}

public class ResultSuccessT
{

  public ResultSuccessT() {
  }
}


static public class ResultSuccessVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
