// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResultFailure : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ResultFailure GetRootAsResultFailure(ByteBuffer _bb) { return GetRootAsResultFailure(_bb, new ResultFailure()); }
  public static ResultFailure GetRootAsResultFailure(ByteBuffer _bb, ResultFailure obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResultFailure __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Reason { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<CardGameUtils.Packets.Server.ResultFailure> CreateResultFailure(FlatBufferBuilder builder,
      StringOffset reasonOffset = default(StringOffset)) {
    builder.StartTable(1);
    ResultFailure.AddReason(builder, reasonOffset);
    return ResultFailure.EndResultFailure(builder);
  }

  public static void StartResultFailure(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(0, reasonOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Server.ResultFailure> EndResultFailure(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ResultFailure>(o);
  }
  public ResultFailureT UnPack() {
    var _o = new ResultFailureT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResultFailureT _o) {
    _o.Reason = this.Reason;
  }
  public static Offset<CardGameUtils.Packets.Server.ResultFailure> Pack(FlatBufferBuilder builder, ResultFailureT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ResultFailure>);
    var _reason = _o.Reason == null ? default(StringOffset) : builder.CreateString(_o.Reason);
    return CreateResultFailure(
      builder,
      _reason);
  }
}

public class ResultFailureT
{
  public string Reason { get; set; }

  public ResultFailureT() {
    this.Reason = null;
  }
}


static public class ResultFailureVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Reason*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
