// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

public enum ServerStartResult : byte
{
  NONE = 0,
  ServerStartResultFailure = 1,
  ServerStartResultSuccess = 2,
  ServerStartResultSuccessButWaiting = 3,
};

public class ServerStartResultUnion {
  public ServerStartResult Type { get; set; }
  public object Value { get; set; }

  public ServerStartResultUnion() {
    this.Type = ServerStartResult.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public CardGameUtils.Packets.Server.ServerStartResultFailureT AsServerStartResultFailure() { return this.As<CardGameUtils.Packets.Server.ServerStartResultFailureT>(); }
  public static ServerStartResultUnion FromServerStartResultFailure(CardGameUtils.Packets.Server.ServerStartResultFailureT _serverstartresultfailure) { return new ServerStartResultUnion{ Type = ServerStartResult.ServerStartResultFailure, Value = _serverstartresultfailure }; }
  public CardGameUtils.Packets.Server.ServerStartResultSuccessT AsServerStartResultSuccess() { return this.As<CardGameUtils.Packets.Server.ServerStartResultSuccessT>(); }
  public static ServerStartResultUnion FromServerStartResultSuccess(CardGameUtils.Packets.Server.ServerStartResultSuccessT _serverstartresultsuccess) { return new ServerStartResultUnion{ Type = ServerStartResult.ServerStartResultSuccess, Value = _serverstartresultsuccess }; }
  public CardGameUtils.Packets.Server.ServerStartResultSuccessButWaitingT AsServerStartResultSuccessButWaiting() { return this.As<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaitingT>(); }
  public static ServerStartResultUnion FromServerStartResultSuccessButWaiting(CardGameUtils.Packets.Server.ServerStartResultSuccessButWaitingT _serverstartresultsuccessbutwaiting) { return new ServerStartResultUnion{ Type = ServerStartResult.ServerStartResultSuccessButWaiting, Value = _serverstartresultsuccessbutwaiting }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ServerStartResultUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ServerStartResult.ServerStartResultFailure: return CardGameUtils.Packets.Server.ServerStartResultFailure.Pack(builder, _o.AsServerStartResultFailure()).Value;
      case ServerStartResult.ServerStartResultSuccess: return CardGameUtils.Packets.Server.ServerStartResultSuccess.Pack(builder, _o.AsServerStartResultSuccess()).Value;
      case ServerStartResult.ServerStartResultSuccessButWaiting: return CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting.Pack(builder, _o.AsServerStartResultSuccessButWaiting()).Value;
    }
  }
}



static public class ServerStartResultVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ServerStartResult)typeId)
    {
      case ServerStartResult.ServerStartResultFailure:
        result = CardGameUtils.Packets.Server.ServerStartResultFailureVerify.Verify(verifier, tablePos);
        break;
      case ServerStartResult.ServerStartResultSuccess:
        result = CardGameUtils.Packets.Server.ServerStartResultSuccessVerify.Verify(verifier, tablePos);
        break;
      case ServerStartResult.ServerStartResultSuccessButWaiting:
        result = CardGameUtils.Packets.Server.ServerStartResultSuccessButWaitingVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
