// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerStartResultSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerStartResultSuccess GetRootAsServerStartResultSuccess(ByteBuffer _bb) { return GetRootAsServerStartResultSuccess(_bb, new ServerStartResultSuccess()); }
  public static ServerStartResultSuccess GetRootAsServerStartResultSuccess(ByteBuffer _bb, ServerStartResultSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerStartResultSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoomId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoomIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRoomIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoomIdArray() { return __p.__vector_as_array<byte>(4); }
  public int Port { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CardGameUtils.Packets.Server.ServerStartResultSuccess> CreateServerStartResultSuccess(FlatBufferBuilder builder,
      StringOffset room_idOffset = default(StringOffset),
      int port = 0) {
    builder.StartTable(2);
    ServerStartResultSuccess.AddPort(builder, port);
    ServerStartResultSuccess.AddRoomId(builder, room_idOffset);
    return ServerStartResultSuccess.EndServerStartResultSuccess(builder);
  }

  public static void StartServerStartResultSuccess(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddRoomId(FlatBufferBuilder builder, StringOffset roomIdOffset) { builder.AddOffset(0, roomIdOffset.Value, 0); }
  public static void AddPort(FlatBufferBuilder builder, int port) { builder.AddInt(1, port, 0); }
  public static Offset<CardGameUtils.Packets.Server.ServerStartResultSuccess> EndServerStartResultSuccess(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ServerStartResultSuccess>(o);
  }
  public ServerStartResultSuccessT UnPack() {
    var _o = new ServerStartResultSuccessT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerStartResultSuccessT _o) {
    _o.RoomId = this.RoomId;
    _o.Port = this.Port;
  }
  public static Offset<CardGameUtils.Packets.Server.ServerStartResultSuccess> Pack(FlatBufferBuilder builder, ServerStartResultSuccessT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ServerStartResultSuccess>);
    var _room_id = _o.RoomId == null ? default(StringOffset) : builder.CreateString(_o.RoomId);
    return CreateServerStartResultSuccess(
      builder,
      _room_id,
      _o.Port);
  }
}

public class ServerStartResultSuccessT
{
  public string RoomId { get; set; }
  public int Port { get; set; }

  public ServerStartResultSuccessT() {
    this.RoomId = null;
    this.Port = 0;
  }
}


static public class ServerStartResultSuccessVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*RoomId*/, false)
      && verifier.VerifyField(tablePos, 6 /*Port*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
