// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerArtworksPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerArtworksPacket GetRootAsServerArtworksPacket(ByteBuffer _bb) { return GetRootAsServerArtworksPacket(_bb, new ServerArtworksPacket()); }
  public static ServerArtworksPacket GetRootAsServerArtworksPacket(ByteBuffer _bb, ServerArtworksPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerArtworksPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool SupportsArtworks { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public CardGameUtils.Packets.Server.ArtworkInfo? Artworks(int j) { int o = __p.__offset(6); return o != 0 ? (CardGameUtils.Packets.Server.ArtworkInfo?)(new CardGameUtils.Packets.Server.ArtworkInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ArtworksLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CardGameUtils.Packets.Server.ServerArtworksPacket> CreateServerArtworksPacket(FlatBufferBuilder builder,
      bool supports_artworks = false,
      VectorOffset artworksOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ServerArtworksPacket.AddArtworks(builder, artworksOffset);
    ServerArtworksPacket.AddSupportsArtworks(builder, supports_artworks);
    return ServerArtworksPacket.EndServerArtworksPacket(builder);
  }

  public static void StartServerArtworksPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSupportsArtworks(FlatBufferBuilder builder, bool supportsArtworks) { builder.AddBool(0, supportsArtworks, false); }
  public static void AddArtworks(FlatBufferBuilder builder, VectorOffset artworksOffset) { builder.AddOffset(1, artworksOffset.Value, 0); }
  public static VectorOffset CreateArtworksVector(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Server.ArtworkInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArtworksVectorBlock(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Server.ArtworkInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArtworksVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CardGameUtils.Packets.Server.ArtworkInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArtworksVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CardGameUtils.Packets.Server.ArtworkInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartArtworksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Server.ServerArtworksPacket> EndServerArtworksPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ServerArtworksPacket>(o);
  }
  public ServerArtworksPacketT UnPack() {
    var _o = new ServerArtworksPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerArtworksPacketT _o) {
    _o.SupportsArtworks = this.SupportsArtworks;
    _o.Artworks = new List<CardGameUtils.Packets.Server.ArtworkInfoT>();
    for (var _j = 0; _j < this.ArtworksLength; ++_j) {_o.Artworks.Add(this.Artworks(_j).HasValue ? this.Artworks(_j).Value.UnPack() : null);}
  }
  public static Offset<CardGameUtils.Packets.Server.ServerArtworksPacket> Pack(FlatBufferBuilder builder, ServerArtworksPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ServerArtworksPacket>);
    var _artworks = default(VectorOffset);
    if (_o.Artworks != null) {
      var __artworks = new Offset<CardGameUtils.Packets.Server.ArtworkInfo>[_o.Artworks.Count];
      for (var _j = 0; _j < __artworks.Length; ++_j) { __artworks[_j] = CardGameUtils.Packets.Server.ArtworkInfo.Pack(builder, _o.Artworks[_j]); }
      _artworks = CreateArtworksVector(builder, __artworks);
    }
    return CreateServerArtworksPacket(
      builder,
      _o.SupportsArtworks,
      _artworks);
  }
}

public class ServerArtworksPacketT
{
  public bool SupportsArtworks { get; set; }
  public List<CardGameUtils.Packets.Server.ArtworkInfoT> Artworks { get; set; }

  public ServerArtworksPacketT() {
    this.SupportsArtworks = false;
    this.Artworks = null;
  }
}


static public class ServerArtworksPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SupportsArtworks*/, 1 /*bool*/, 1, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Artworks*/, CardGameUtils.Packets.Server.ArtworkInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
