// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerStartResultSuccessButWaiting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerStartResultSuccessButWaiting GetRootAsServerStartResultSuccessButWaiting(ByteBuffer _bb) { return GetRootAsServerStartResultSuccessButWaiting(_bb, new ServerStartResultSuccessButWaiting()); }
  public static ServerStartResultSuccessButWaiting GetRootAsServerStartResultSuccessButWaiting(ByteBuffer _bb, ServerStartResultSuccessButWaiting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerStartResultSuccessButWaiting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartServerStartResultSuccessButWaiting(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting> EndServerStartResultSuccessButWaiting(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting>(o);
  }
  public ServerStartResultSuccessButWaitingT UnPack() {
    var _o = new ServerStartResultSuccessButWaitingT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerStartResultSuccessButWaitingT _o) {
  }
  public static Offset<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting> Pack(FlatBufferBuilder builder, ServerStartResultSuccessButWaitingT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting>);
    StartServerStartResultSuccessButWaiting(builder);
    return EndServerStartResultSuccessButWaiting(builder);
  }
}

public class ServerStartResultSuccessButWaitingT
{

  public ServerStartResultSuccessButWaitingT() {
  }
}


static public class ServerStartResultSuccessButWaitingVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
