// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerRoomsPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerRoomsPacket GetRootAsServerRoomsPacket(ByteBuffer _bb) { return GetRootAsServerRoomsPacket(_bb, new ServerRoomsPacket()); }
  public static ServerRoomsPacket GetRootAsServerRoomsPacket(ByteBuffer _bb, ServerRoomsPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerRoomsPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Rooms(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int RoomsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CardGameUtils.Packets.Server.ServerRoomsPacket> CreateServerRoomsPacket(FlatBufferBuilder builder,
      VectorOffset roomsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ServerRoomsPacket.AddRooms(builder, roomsOffset);
    return ServerRoomsPacket.EndServerRoomsPacket(builder);
  }

  public static void StartServerRoomsPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRooms(FlatBufferBuilder builder, VectorOffset roomsOffset) { builder.AddOffset(0, roomsOffset.Value, 0); }
  public static VectorOffset CreateRoomsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRoomsVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRoomsVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRoomsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRoomsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Server.ServerRoomsPacket> EndServerRoomsPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ServerRoomsPacket>(o);
  }
  public ServerRoomsPacketT UnPack() {
    var _o = new ServerRoomsPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerRoomsPacketT _o) {
    _o.Rooms = new List<string>();
    for (var _j = 0; _j < this.RoomsLength; ++_j) {_o.Rooms.Add(this.Rooms(_j));}
  }
  public static Offset<CardGameUtils.Packets.Server.ServerRoomsPacket> Pack(FlatBufferBuilder builder, ServerRoomsPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ServerRoomsPacket>);
    var _rooms = default(VectorOffset);
    if (_o.Rooms != null) {
      var __rooms = new StringOffset[_o.Rooms.Count];
      for (var _j = 0; _j < __rooms.Length; ++_j) { __rooms[_j] = builder.CreateString(_o.Rooms[_j]); }
      _rooms = CreateRoomsVector(builder, __rooms);
    }
    return CreateServerRoomsPacket(
      builder,
      _rooms);
  }
}

public class ServerRoomsPacketT
{
  public List<string> Rooms { get; set; }

  public ServerRoomsPacketT() {
    this.Rooms = null;
  }
}


static public class ServerRoomsPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*Rooms*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
