// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Server
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerStartPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerStartPacket GetRootAsServerStartPacket(ByteBuffer _bb) { return GetRootAsServerStartPacket(_bb, new ServerStartPacket()); }
  public static ServerStartPacket GetRootAsServerStartPacket(ByteBuffer _bb, ServerStartPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerStartPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Packets.Server.ServerStartResult ResultType { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Packets.Server.ServerStartResult)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Packets.Server.ServerStartResult.NONE; } }
  public TTable? Result<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public CardGameUtils.Packets.Server.ServerStartResultFailure ResultAsServerStartResultFailure() { return Result<CardGameUtils.Packets.Server.ServerStartResultFailure>().Value; }
  public CardGameUtils.Packets.Server.ServerStartResultSuccess ResultAsServerStartResultSuccess() { return Result<CardGameUtils.Packets.Server.ServerStartResultSuccess>().Value; }
  public CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting ResultAsServerStartResultSuccessButWaiting() { return Result<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting>().Value; }

  public static Offset<CardGameUtils.Packets.Server.ServerStartPacket> CreateServerStartPacket(FlatBufferBuilder builder,
      CardGameUtils.Packets.Server.ServerStartResult result_type = CardGameUtils.Packets.Server.ServerStartResult.NONE,
      int resultOffset = 0) {
    builder.StartTable(2);
    ServerStartPacket.AddResult(builder, resultOffset);
    ServerStartPacket.AddResultType(builder, result_type);
    return ServerStartPacket.EndServerStartPacket(builder);
  }

  public static void StartServerStartPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddResultType(FlatBufferBuilder builder, CardGameUtils.Packets.Server.ServerStartResult resultType) { builder.AddByte(0, (byte)resultType, 0); }
  public static void AddResult(FlatBufferBuilder builder, int resultOffset) { builder.AddOffset(1, resultOffset, 0); }
  public static Offset<CardGameUtils.Packets.Server.ServerStartPacket> EndServerStartPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Server.ServerStartPacket>(o);
  }
  public ServerStartPacketT UnPack() {
    var _o = new ServerStartPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerStartPacketT _o) {
    _o.Result = new CardGameUtils.Packets.Server.ServerStartResultUnion();
    _o.Result.Type = this.ResultType;
    switch (this.ResultType) {
      default: break;
      case CardGameUtils.Packets.Server.ServerStartResult.ServerStartResultFailure:
        _o.Result.Value = this.Result<CardGameUtils.Packets.Server.ServerStartResultFailure>().HasValue ? this.Result<CardGameUtils.Packets.Server.ServerStartResultFailure>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ServerStartResult.ServerStartResultSuccess:
        _o.Result.Value = this.Result<CardGameUtils.Packets.Server.ServerStartResultSuccess>().HasValue ? this.Result<CardGameUtils.Packets.Server.ServerStartResultSuccess>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Server.ServerStartResult.ServerStartResultSuccessButWaiting:
        _o.Result.Value = this.Result<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting>().HasValue ? this.Result<CardGameUtils.Packets.Server.ServerStartResultSuccessButWaiting>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<CardGameUtils.Packets.Server.ServerStartPacket> Pack(FlatBufferBuilder builder, ServerStartPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Server.ServerStartPacket>);
    var _result_type = _o.Result == null ? CardGameUtils.Packets.Server.ServerStartResult.NONE : _o.Result.Type;
    var _result = _o.Result == null ? 0 : CardGameUtils.Packets.Server.ServerStartResultUnion.Pack(builder, _o.Result);
    return CreateServerStartPacket(
      builder,
      _result_type,
      _result);
  }
}

public class ServerStartPacketT
{
  public CardGameUtils.Packets.Server.ServerStartResultUnion Result { get; set; }

  public ServerStartPacketT() {
    this.Result = null;
  }
}


static public class ServerStartPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResultType*/, 1 /*CardGameUtils.Packets.Server.ServerStartResult*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Result*/, CardGameUtils.Packets.Server.ServerStartResultVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
