// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Shared
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DeckInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static DeckInfo GetRootAsDeckInfo(ByteBuffer _bb) { return GetRootAsDeckInfo(_bb, new DeckInfo()); }
  public static DeckInfo GetRootAsDeckInfo(ByteBuffer _bb, DeckInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeckInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public CardGameUtils.Shared.CardInfo? Cards(int j) { int o = __p.__offset(6); return o != 0 ? (CardGameUtils.Shared.CardInfo?)(new CardGameUtils.Shared.CardInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CardsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public CardGameUtils.Constants.PlayerClass PlayerClass { get { int o = __p.__offset(8); return o != 0 ? (CardGameUtils.Constants.PlayerClass)__p.bb.GetSbyte(o + __p.bb_pos) : CardGameUtils.Constants.PlayerClass.UNKNOWN; } }
  public CardGameUtils.Shared.CardInfo? Ability { get { int o = __p.__offset(10); return o != 0 ? (CardGameUtils.Shared.CardInfo?)(new CardGameUtils.Shared.CardInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public CardGameUtils.Shared.CardInfo? Quest { get { int o = __p.__offset(12); return o != 0 ? (CardGameUtils.Shared.CardInfo?)(new CardGameUtils.Shared.CardInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CardGameUtils.Shared.DeckInfo> CreateDeckInfo(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset cardsOffset = default(VectorOffset),
      CardGameUtils.Constants.PlayerClass player_class = CardGameUtils.Constants.PlayerClass.UNKNOWN,
      Offset<CardGameUtils.Shared.CardInfo> abilityOffset = default(Offset<CardGameUtils.Shared.CardInfo>),
      Offset<CardGameUtils.Shared.CardInfo> questOffset = default(Offset<CardGameUtils.Shared.CardInfo>)) {
    builder.StartTable(5);
    DeckInfo.AddQuest(builder, questOffset);
    DeckInfo.AddAbility(builder, abilityOffset);
    DeckInfo.AddCards(builder, cardsOffset);
    DeckInfo.AddName(builder, nameOffset);
    DeckInfo.AddPlayerClass(builder, player_class);
    return DeckInfo.EndDeckInfo(builder);
  }

  public static void StartDeckInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddCards(FlatBufferBuilder builder, VectorOffset cardsOffset) { builder.AddOffset(1, cardsOffset.Value, 0); }
  public static VectorOffset CreateCardsVector(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CardGameUtils.Shared.CardInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CardGameUtils.Shared.CardInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCardsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPlayerClass(FlatBufferBuilder builder, CardGameUtils.Constants.PlayerClass playerClass) { builder.AddSbyte(2, (sbyte)playerClass, 0); }
  public static void AddAbility(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo> abilityOffset) { builder.AddOffset(3, abilityOffset.Value, 0); }
  public static void AddQuest(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo> questOffset) { builder.AddOffset(4, questOffset.Value, 0); }
  public static Offset<CardGameUtils.Shared.DeckInfo> EndDeckInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Shared.DeckInfo>(o);
  }
  public DeckInfoT UnPack() {
    var _o = new DeckInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DeckInfoT _o) {
    _o.Name = this.Name;
    _o.Cards = new List<CardGameUtils.Shared.CardInfoT>();
    for (var _j = 0; _j < this.CardsLength; ++_j) {_o.Cards.Add(this.Cards(_j).HasValue ? this.Cards(_j).Value.UnPack() : null);}
    _o.PlayerClass = this.PlayerClass;
    _o.Ability = this.Ability.HasValue ? this.Ability.Value.UnPack() : null;
    _o.Quest = this.Quest.HasValue ? this.Quest.Value.UnPack() : null;
  }
  public static Offset<CardGameUtils.Shared.DeckInfo> Pack(FlatBufferBuilder builder, DeckInfoT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Shared.DeckInfo>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _cards = default(VectorOffset);
    if (_o.Cards != null) {
      var __cards = new Offset<CardGameUtils.Shared.CardInfo>[_o.Cards.Count];
      for (var _j = 0; _j < __cards.Length; ++_j) { __cards[_j] = CardGameUtils.Shared.CardInfo.Pack(builder, _o.Cards[_j]); }
      _cards = CreateCardsVector(builder, __cards);
    }
    var _ability = _o.Ability == null ? default(Offset<CardGameUtils.Shared.CardInfo>) : CardGameUtils.Shared.CardInfo.Pack(builder, _o.Ability);
    var _quest = _o.Quest == null ? default(Offset<CardGameUtils.Shared.CardInfo>) : CardGameUtils.Shared.CardInfo.Pack(builder, _o.Quest);
    return CreateDeckInfo(
      builder,
      _name,
      _cards,
      _o.PlayerClass,
      _ability,
      _quest);
  }
}

public class DeckInfoT
{
  public string Name { get; set; }
  public List<CardGameUtils.Shared.CardInfoT> Cards { get; set; }
  public CardGameUtils.Constants.PlayerClass PlayerClass { get; set; }
  public CardGameUtils.Shared.CardInfoT Ability { get; set; }
  public CardGameUtils.Shared.CardInfoT Quest { get; set; }

  public DeckInfoT() {
    this.Name = null;
    this.Cards = null;
    this.PlayerClass = CardGameUtils.Constants.PlayerClass.UNKNOWN;
    this.Ability = null;
    this.Quest = null;
  }
}


static public class DeckInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Cards*/, CardGameUtils.Shared.CardInfoVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*PlayerClass*/, 1 /*CardGameUtils.Constants.PlayerClass*/, 1, false)
      && verifier.VerifyTable(tablePos, 10 /*Ability*/, CardGameUtils.Shared.CardInfoVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 12 /*Quest*/, CardGameUtils.Shared.CardInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
