// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Shared
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SpellSpecifics : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SpellSpecifics GetRootAsSpellSpecifics(ByteBuffer _bb) { return GetRootAsSpellSpecifics(_bb, new SpellSpecifics()); }
  public static SpellSpecifics GetRootAsSpellSpecifics(ByteBuffer _bb, SpellSpecifics obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SpellSpecifics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Cost { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BaseCost { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool IsClassAbility { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanBeClassAbility { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<CardGameUtils.Shared.SpellSpecifics> CreateSpellSpecifics(FlatBufferBuilder builder,
      int cost = 0,
      int base_cost = 0,
      bool is_class_ability = false,
      bool can_be_class_ability = false) {
    builder.StartTable(4);
    SpellSpecifics.AddBaseCost(builder, base_cost);
    SpellSpecifics.AddCost(builder, cost);
    SpellSpecifics.AddCanBeClassAbility(builder, can_be_class_ability);
    SpellSpecifics.AddIsClassAbility(builder, is_class_ability);
    return SpellSpecifics.EndSpellSpecifics(builder);
  }

  public static void StartSpellSpecifics(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCost(FlatBufferBuilder builder, int cost) { builder.AddInt(0, cost, 0); }
  public static void AddBaseCost(FlatBufferBuilder builder, int baseCost) { builder.AddInt(1, baseCost, 0); }
  public static void AddIsClassAbility(FlatBufferBuilder builder, bool isClassAbility) { builder.AddBool(2, isClassAbility, false); }
  public static void AddCanBeClassAbility(FlatBufferBuilder builder, bool canBeClassAbility) { builder.AddBool(3, canBeClassAbility, false); }
  public static Offset<CardGameUtils.Shared.SpellSpecifics> EndSpellSpecifics(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Shared.SpellSpecifics>(o);
  }
  public SpellSpecificsT UnPack() {
    var _o = new SpellSpecificsT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SpellSpecificsT _o) {
    _o.Cost = this.Cost;
    _o.BaseCost = this.BaseCost;
    _o.IsClassAbility = this.IsClassAbility;
    _o.CanBeClassAbility = this.CanBeClassAbility;
  }
  public static Offset<CardGameUtils.Shared.SpellSpecifics> Pack(FlatBufferBuilder builder, SpellSpecificsT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Shared.SpellSpecifics>);
    return CreateSpellSpecifics(
      builder,
      _o.Cost,
      _o.BaseCost,
      _o.IsClassAbility,
      _o.CanBeClassAbility);
  }
}

public class SpellSpecificsT
{
  public int Cost { get; set; }
  public int BaseCost { get; set; }
  public bool IsClassAbility { get; set; }
  public bool CanBeClassAbility { get; set; }

  public SpellSpecificsT() {
    this.Cost = 0;
    this.BaseCost = 0;
    this.IsClassAbility = false;
    this.CanBeClassAbility = false;
  }
}


static public class SpellSpecificsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Cost*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*BaseCost*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*IsClassAbility*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*CanBeClassAbility*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
