// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

public enum ClientContent : byte
{
  NONE = 0,
  surrender = 1,
  getoptions = 2,
  selectoption = 3,
  yesno = 4,
  selectcards = 5,
  customselectcards = 6,
  customselectintermediate = 7,
  selectzone = 8,
  pass = 9,
  viewgrave = 10,
};

public class ClientContentUnion {
  public ClientContent Type { get; set; }
  public object Value { get; set; }

  public ClientContentUnion() {
    this.Type = ClientContent.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public CardGameUtils.Packets.Duel.ClientSurrenderPacketT Assurrender() { return this.As<CardGameUtils.Packets.Duel.ClientSurrenderPacketT>(); }
  public static ClientContentUnion Fromsurrender(CardGameUtils.Packets.Duel.ClientSurrenderPacketT _surrender) { return new ClientContentUnion{ Type = ClientContent.surrender, Value = _surrender }; }
  public CardGameUtils.Packets.Duel.ClientGetOptionsPacketT Asgetoptions() { return this.As<CardGameUtils.Packets.Duel.ClientGetOptionsPacketT>(); }
  public static ClientContentUnion Fromgetoptions(CardGameUtils.Packets.Duel.ClientGetOptionsPacketT _getoptions) { return new ClientContentUnion{ Type = ClientContent.getoptions, Value = _getoptions }; }
  public CardGameUtils.Packets.Duel.ClientSelectOptionPacketT Asselectoption() { return this.As<CardGameUtils.Packets.Duel.ClientSelectOptionPacketT>(); }
  public static ClientContentUnion Fromselectoption(CardGameUtils.Packets.Duel.ClientSelectOptionPacketT _selectoption) { return new ClientContentUnion{ Type = ClientContent.selectoption, Value = _selectoption }; }
  public CardGameUtils.Packets.Duel.ClientYesNoPacketT Asyesno() { return this.As<CardGameUtils.Packets.Duel.ClientYesNoPacketT>(); }
  public static ClientContentUnion Fromyesno(CardGameUtils.Packets.Duel.ClientYesNoPacketT _yesno) { return new ClientContentUnion{ Type = ClientContent.yesno, Value = _yesno }; }
  public CardGameUtils.Packets.Duel.ClientSelectCardsPacketT Asselectcards() { return this.As<CardGameUtils.Packets.Duel.ClientSelectCardsPacketT>(); }
  public static ClientContentUnion Fromselectcards(CardGameUtils.Packets.Duel.ClientSelectCardsPacketT _selectcards) { return new ClientContentUnion{ Type = ClientContent.selectcards, Value = _selectcards }; }
  public CardGameUtils.Packets.Duel.ClientCustomSelectCardsPacketT Ascustomselectcards() { return this.As<CardGameUtils.Packets.Duel.ClientCustomSelectCardsPacketT>(); }
  public static ClientContentUnion Fromcustomselectcards(CardGameUtils.Packets.Duel.ClientCustomSelectCardsPacketT _customselectcards) { return new ClientContentUnion{ Type = ClientContent.customselectcards, Value = _customselectcards }; }
  public CardGameUtils.Packets.Duel.ClientCustomSelectIntermediatePacketT Ascustomselectintermediate() { return this.As<CardGameUtils.Packets.Duel.ClientCustomSelectIntermediatePacketT>(); }
  public static ClientContentUnion Fromcustomselectintermediate(CardGameUtils.Packets.Duel.ClientCustomSelectIntermediatePacketT _customselectintermediate) { return new ClientContentUnion{ Type = ClientContent.customselectintermediate, Value = _customselectintermediate }; }
  public CardGameUtils.Packets.Duel.ClientSelectZonePacketT Asselectzone() { return this.As<CardGameUtils.Packets.Duel.ClientSelectZonePacketT>(); }
  public static ClientContentUnion Fromselectzone(CardGameUtils.Packets.Duel.ClientSelectZonePacketT _selectzone) { return new ClientContentUnion{ Type = ClientContent.selectzone, Value = _selectzone }; }
  public CardGameUtils.Packets.Duel.ClientPassPacketT Aspass() { return this.As<CardGameUtils.Packets.Duel.ClientPassPacketT>(); }
  public static ClientContentUnion Frompass(CardGameUtils.Packets.Duel.ClientPassPacketT _pass) { return new ClientContentUnion{ Type = ClientContent.pass, Value = _pass }; }
  public CardGameUtils.Packets.Duel.ClientViewGravePacketT Asviewgrave() { return this.As<CardGameUtils.Packets.Duel.ClientViewGravePacketT>(); }
  public static ClientContentUnion Fromviewgrave(CardGameUtils.Packets.Duel.ClientViewGravePacketT _viewgrave) { return new ClientContentUnion{ Type = ClientContent.viewgrave, Value = _viewgrave }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ClientContentUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ClientContent.surrender: return CardGameUtils.Packets.Duel.ClientSurrenderPacket.Pack(builder, _o.Assurrender()).Value;
      case ClientContent.getoptions: return CardGameUtils.Packets.Duel.ClientGetOptionsPacket.Pack(builder, _o.Asgetoptions()).Value;
      case ClientContent.selectoption: return CardGameUtils.Packets.Duel.ClientSelectOptionPacket.Pack(builder, _o.Asselectoption()).Value;
      case ClientContent.yesno: return CardGameUtils.Packets.Duel.ClientYesNoPacket.Pack(builder, _o.Asyesno()).Value;
      case ClientContent.selectcards: return CardGameUtils.Packets.Duel.ClientSelectCardsPacket.Pack(builder, _o.Asselectcards()).Value;
      case ClientContent.customselectcards: return CardGameUtils.Packets.Duel.ClientCustomSelectCardsPacket.Pack(builder, _o.Ascustomselectcards()).Value;
      case ClientContent.customselectintermediate: return CardGameUtils.Packets.Duel.ClientCustomSelectIntermediatePacket.Pack(builder, _o.Ascustomselectintermediate()).Value;
      case ClientContent.selectzone: return CardGameUtils.Packets.Duel.ClientSelectZonePacket.Pack(builder, _o.Asselectzone()).Value;
      case ClientContent.pass: return CardGameUtils.Packets.Duel.ClientPassPacket.Pack(builder, _o.Aspass()).Value;
      case ClientContent.viewgrave: return CardGameUtils.Packets.Duel.ClientViewGravePacket.Pack(builder, _o.Asviewgrave()).Value;
    }
  }
}



static public class ClientContentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ClientContent)typeId)
    {
      case ClientContent.surrender:
        result = CardGameUtils.Packets.Duel.ClientSurrenderPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.getoptions:
        result = CardGameUtils.Packets.Duel.ClientGetOptionsPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.selectoption:
        result = CardGameUtils.Packets.Duel.ClientSelectOptionPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.yesno:
        result = CardGameUtils.Packets.Duel.ClientYesNoPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.selectcards:
        result = CardGameUtils.Packets.Duel.ClientSelectCardsPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.customselectcards:
        result = CardGameUtils.Packets.Duel.ClientCustomSelectCardsPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.customselectintermediate:
        result = CardGameUtils.Packets.Duel.ClientCustomSelectIntermediatePacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.selectzone:
        result = CardGameUtils.Packets.Duel.ClientSelectZonePacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.pass:
        result = CardGameUtils.Packets.Duel.ClientPassPacketVerify.Verify(verifier, tablePos);
        break;
      case ClientContent.viewgrave:
        result = CardGameUtils.Packets.Duel.ClientViewGravePacketVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
