// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientViewGravePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientViewGravePacket GetRootAsClientViewGravePacket(ByteBuffer _bb) { return GetRootAsClientViewGravePacket(_bb, new ClientViewGravePacket()); }
  public static ClientViewGravePacket GetRootAsClientViewGravePacket(ByteBuffer _bb, ClientViewGravePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientViewGravePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool OfOpponent { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<CardGameUtils.Packets.Duel.ClientViewGravePacket> CreateClientViewGravePacket(FlatBufferBuilder builder,
      bool of_opponent = false) {
    builder.StartTable(1);
    ClientViewGravePacket.AddOfOpponent(builder, of_opponent);
    return ClientViewGravePacket.EndClientViewGravePacket(builder);
  }

  public static void StartClientViewGravePacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOfOpponent(FlatBufferBuilder builder, bool ofOpponent) { builder.AddBool(0, ofOpponent, false); }
  public static Offset<CardGameUtils.Packets.Duel.ClientViewGravePacket> EndClientViewGravePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ClientViewGravePacket>(o);
  }
  public ClientViewGravePacketT UnPack() {
    var _o = new ClientViewGravePacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientViewGravePacketT _o) {
    _o.OfOpponent = this.OfOpponent;
  }
  public static Offset<CardGameUtils.Packets.Duel.ClientViewGravePacket> Pack(FlatBufferBuilder builder, ClientViewGravePacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ClientViewGravePacket>);
    return CreateClientViewGravePacket(
      builder,
      _o.OfOpponent);
  }
}

public class ClientViewGravePacketT
{
  public bool OfOpponent { get; set; }

  public ClientViewGravePacketT() {
    this.OfOpponent = false;
  }
}


static public class ClientViewGravePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*OfOpponent*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
