// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientSelectCardsPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientSelectCardsPacket GetRootAsClientSelectCardsPacket(ByteBuffer _bb) { return GetRootAsClientSelectCardsPacket(_bb, new ClientSelectCardsPacket()); }
  public static ClientSelectCardsPacket GetRootAsClientSelectCardsPacket(ByteBuffer _bb, ClientSelectCardsPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientSelectCardsPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uids(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int UidsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetUidsBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetUidsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetUidsArray() { return __p.__vector_as_array<int>(4); }

  public static Offset<CardGameUtils.Packets.Duel.ClientSelectCardsPacket> CreateClientSelectCardsPacket(FlatBufferBuilder builder,
      VectorOffset uidsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ClientSelectCardsPacket.AddUids(builder, uidsOffset);
    return ClientSelectCardsPacket.EndClientSelectCardsPacket(builder);
  }

  public static void StartClientSelectCardsPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUids(FlatBufferBuilder builder, VectorOffset uidsOffset) { builder.AddOffset(0, uidsOffset.Value, 0); }
  public static VectorOffset CreateUidsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUidsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUidsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUidsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUidsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectCardsPacket> EndClientSelectCardsPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ClientSelectCardsPacket>(o);
  }
  public ClientSelectCardsPacketT UnPack() {
    var _o = new ClientSelectCardsPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientSelectCardsPacketT _o) {
    _o.Uids = new List<int>();
    for (var _j = 0; _j < this.UidsLength; ++_j) {_o.Uids.Add(this.Uids(_j));}
  }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectCardsPacket> Pack(FlatBufferBuilder builder, ClientSelectCardsPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ClientSelectCardsPacket>);
    var _uids = default(VectorOffset);
    if (_o.Uids != null) {
      var __uids = _o.Uids.ToArray();
      _uids = CreateUidsVector(builder, __uids);
    }
    return CreateClientSelectCardsPacket(
      builder,
      _uids);
  }
}

public class ClientSelectCardsPacketT
{
  public List<int> Uids { get; set; }

  public ClientSelectCardsPacketT() {
    this.Uids = null;
  }
}


static public class ClientSelectCardsPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Uids*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
