// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientSelectZonePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientSelectZonePacket GetRootAsClientSelectZonePacket(ByteBuffer _bb) { return GetRootAsClientSelectZonePacket(_bb, new ClientSelectZonePacket()); }
  public static ClientSelectZonePacket GetRootAsClientSelectZonePacket(ByteBuffer _bb, ClientSelectZonePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientSelectZonePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Zone { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CardGameUtils.Packets.Duel.ClientSelectZonePacket> CreateClientSelectZonePacket(FlatBufferBuilder builder,
      int zone = 0) {
    builder.StartTable(1);
    ClientSelectZonePacket.AddZone(builder, zone);
    return ClientSelectZonePacket.EndClientSelectZonePacket(builder);
  }

  public static void StartClientSelectZonePacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddZone(FlatBufferBuilder builder, int zone) { builder.AddInt(0, zone, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectZonePacket> EndClientSelectZonePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ClientSelectZonePacket>(o);
  }
  public ClientSelectZonePacketT UnPack() {
    var _o = new ClientSelectZonePacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientSelectZonePacketT _o) {
    _o.Zone = this.Zone;
  }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectZonePacket> Pack(FlatBufferBuilder builder, ClientSelectZonePacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ClientSelectZonePacket>);
    return CreateClientSelectZonePacket(
      builder,
      _o.Zone);
  }
}

public class ClientSelectZonePacketT
{
  public int Zone { get; set; }

  public ClientSelectZonePacketT() {
    this.Zone = 0;
  }
}


static public class ClientSelectZonePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Zone*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
