// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClientSelectOptionPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClientSelectOptionPacket GetRootAsClientSelectOptionPacket(ByteBuffer _bb) { return GetRootAsClientSelectOptionPacket(_bb, new ClientSelectOptionPacket()); }
  public static ClientSelectOptionPacket GetRootAsClientSelectOptionPacket(ByteBuffer _bb, ClientSelectOptionPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientSelectOptionPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Constants.Location Location { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Constants.Location)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Constants.Location.UNKNOWN; } }
  public int Uid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CardGameUtils.Shared.CardAction? Action { get { int o = __p.__offset(8); return o != 0 ? (CardGameUtils.Shared.CardAction?)(new CardGameUtils.Shared.CardAction()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CardGameUtils.Packets.Duel.ClientSelectOptionPacket> CreateClientSelectOptionPacket(FlatBufferBuilder builder,
      CardGameUtils.Constants.Location location = CardGameUtils.Constants.Location.UNKNOWN,
      int uid = 0,
      Offset<CardGameUtils.Shared.CardAction> actionOffset = default(Offset<CardGameUtils.Shared.CardAction>)) {
    builder.StartTable(3);
    ClientSelectOptionPacket.AddAction(builder, actionOffset);
    ClientSelectOptionPacket.AddUid(builder, uid);
    ClientSelectOptionPacket.AddLocation(builder, location);
    return ClientSelectOptionPacket.EndClientSelectOptionPacket(builder);
  }

  public static void StartClientSelectOptionPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddLocation(FlatBufferBuilder builder, CardGameUtils.Constants.Location location) { builder.AddByte(0, (byte)location, 0); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(1, uid, 0); }
  public static void AddAction(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardAction> actionOffset) { builder.AddOffset(2, actionOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectOptionPacket> EndClientSelectOptionPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ClientSelectOptionPacket>(o);
  }
  public ClientSelectOptionPacketT UnPack() {
    var _o = new ClientSelectOptionPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClientSelectOptionPacketT _o) {
    _o.Location = this.Location;
    _o.Uid = this.Uid;
    _o.Action = this.Action.HasValue ? this.Action.Value.UnPack() : null;
  }
  public static Offset<CardGameUtils.Packets.Duel.ClientSelectOptionPacket> Pack(FlatBufferBuilder builder, ClientSelectOptionPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ClientSelectOptionPacket>);
    var _action = _o.Action == null ? default(Offset<CardGameUtils.Shared.CardAction>) : CardGameUtils.Shared.CardAction.Pack(builder, _o.Action);
    return CreateClientSelectOptionPacket(
      builder,
      _o.Location,
      _o.Uid,
      _action);
  }
}

public class ClientSelectOptionPacketT
{
  public CardGameUtils.Constants.Location Location { get; set; }
  public int Uid { get; set; }
  public CardGameUtils.Shared.CardActionT Action { get; set; }

  public ClientSelectOptionPacketT() {
    this.Location = CardGameUtils.Constants.Location.UNKNOWN;
    this.Uid = 0;
    this.Action = null;
  }
}


static public class ClientSelectOptionPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Location*/, 1 /*CardGameUtils.Constants.Location*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Uid*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 8 /*Action*/, CardGameUtils.Shared.CardActionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
