// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldCardInfoEmpty : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static FieldCardInfoEmpty GetRootAsFieldCardInfoEmpty(ByteBuffer _bb) { return GetRootAsFieldCardInfoEmpty(_bb, new FieldCardInfoEmpty()); }
  public static FieldCardInfoEmpty GetRootAsFieldCardInfoEmpty(ByteBuffer _bb, FieldCardInfoEmpty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldCardInfoEmpty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartFieldCardInfoEmpty(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<CardGameUtils.Packets.Duel.FieldCardInfoEmpty> EndFieldCardInfoEmpty(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.FieldCardInfoEmpty>(o);
  }
  public FieldCardInfoEmptyT UnPack() {
    var _o = new FieldCardInfoEmptyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldCardInfoEmptyT _o) {
  }
  public static Offset<CardGameUtils.Packets.Duel.FieldCardInfoEmpty> Pack(FlatBufferBuilder builder, FieldCardInfoEmptyT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.FieldCardInfoEmpty>);
    StartFieldCardInfoEmpty(builder);
    return EndFieldCardInfoEmpty(builder);
  }
}

public class FieldCardInfoEmptyT
{

  public FieldCardInfoEmptyT() {
  }
}


static public class FieldCardInfoEmptyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
