// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

public enum GameResult : sbyte
{
  UNKNOWN = 0,
  Lost = 1,
  Draw = 2,
  Won = 3,
};


}
