// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Replay : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Replay GetRootAsReplay(ByteBuffer _bb) { return GetRootAsReplay(_bb, new Replay()); }
  public static Replay GetRootAsReplay(ByteBuffer _bb, Replay obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Replay __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string CmdlineArgs(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int CmdlineArgsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Seed { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CardGameUtils.Packets.Duel.ReplayAction? Actions(int j) { int o = __p.__offset(8); return o != 0 ? (CardGameUtils.Packets.Duel.ReplayAction?)(new CardGameUtils.Packets.Duel.ReplayAction()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ActionsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CardGameUtils.Packets.Duel.Replay> CreateReplay(FlatBufferBuilder builder,
      VectorOffset cmdline_argsOffset = default(VectorOffset),
      int seed = 0,
      VectorOffset actionsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    Replay.AddActions(builder, actionsOffset);
    Replay.AddSeed(builder, seed);
    Replay.AddCmdlineArgs(builder, cmdline_argsOffset);
    return Replay.EndReplay(builder);
  }

  public static void StartReplay(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddCmdlineArgs(FlatBufferBuilder builder, VectorOffset cmdlineArgsOffset) { builder.AddOffset(0, cmdlineArgsOffset.Value, 0); }
  public static VectorOffset CreateCmdlineArgsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCmdlineArgsVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCmdlineArgsVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCmdlineArgsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCmdlineArgsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSeed(FlatBufferBuilder builder, int seed) { builder.AddInt(1, seed, 0); }
  public static void AddActions(FlatBufferBuilder builder, VectorOffset actionsOffset) { builder.AddOffset(2, actionsOffset.Value, 0); }
  public static VectorOffset CreateActionsVector(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Duel.ReplayAction>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, Offset<CardGameUtils.Packets.Duel.ReplayAction>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CardGameUtils.Packets.Duel.ReplayAction>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CardGameUtils.Packets.Duel.ReplayAction>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartActionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Duel.Replay> EndReplay(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.Replay>(o);
  }
  public ReplayT UnPack() {
    var _o = new ReplayT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ReplayT _o) {
    _o.CmdlineArgs = new List<string>();
    for (var _j = 0; _j < this.CmdlineArgsLength; ++_j) {_o.CmdlineArgs.Add(this.CmdlineArgs(_j));}
    _o.Seed = this.Seed;
    _o.Actions = new List<CardGameUtils.Packets.Duel.ReplayActionT>();
    for (var _j = 0; _j < this.ActionsLength; ++_j) {_o.Actions.Add(this.Actions(_j).HasValue ? this.Actions(_j).Value.UnPack() : null);}
  }
  public static Offset<CardGameUtils.Packets.Duel.Replay> Pack(FlatBufferBuilder builder, ReplayT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.Replay>);
    var _cmdline_args = default(VectorOffset);
    if (_o.CmdlineArgs != null) {
      var __cmdline_args = new StringOffset[_o.CmdlineArgs.Count];
      for (var _j = 0; _j < __cmdline_args.Length; ++_j) { __cmdline_args[_j] = builder.CreateString(_o.CmdlineArgs[_j]); }
      _cmdline_args = CreateCmdlineArgsVector(builder, __cmdline_args);
    }
    var _actions = default(VectorOffset);
    if (_o.Actions != null) {
      var __actions = new Offset<CardGameUtils.Packets.Duel.ReplayAction>[_o.Actions.Count];
      for (var _j = 0; _j < __actions.Length; ++_j) { __actions[_j] = CardGameUtils.Packets.Duel.ReplayAction.Pack(builder, _o.Actions[_j]); }
      _actions = CreateActionsVector(builder, __actions);
    }
    return CreateReplay(
      builder,
      _cmdline_args,
      _o.Seed,
      _actions);
  }
}

public class ReplayT
{
  public List<string> CmdlineArgs { get; set; }
  public int Seed { get; set; }
  public List<CardGameUtils.Packets.Duel.ReplayActionT> Actions { get; set; }

  public ReplayT() {
    this.CmdlineArgs = null;
    this.Seed = 0;
    this.Actions = null;
  }
}


static public class ReplayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*CmdlineArgs*/, false)
      && verifier.VerifyField(tablePos, 6 /*Seed*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Actions*/, CardGameUtils.Packets.Duel.ReplayActionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
