// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ReplayAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ReplayAction GetRootAsReplayAction(ByteBuffer _bb) { return GetRootAsReplayAction(_bb, new ReplayAction()); }
  public static ReplayAction GetRootAsReplayAction(ByteBuffer _bb, ReplayAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReplayAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Player { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CardGameUtils.Packets.Duel.ReplayActionPacket PacketType { get { int o = __p.__offset(6); return o != 0 ? (CardGameUtils.Packets.Duel.ReplayActionPacket)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Packets.Duel.ReplayActionPacket.NONE; } }
  public TTable? Packet<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public CardGameUtils.Packets.Duel.ClientPacket PacketAsclient() { return Packet<CardGameUtils.Packets.Duel.ClientPacket>().Value; }
  public CardGameUtils.Packets.Duel.ServerPacket PacketAsserver() { return Packet<CardGameUtils.Packets.Duel.ServerPacket>().Value; }

  public static Offset<CardGameUtils.Packets.Duel.ReplayAction> CreateReplayAction(FlatBufferBuilder builder,
      int player = 0,
      CardGameUtils.Packets.Duel.ReplayActionPacket packet_type = CardGameUtils.Packets.Duel.ReplayActionPacket.NONE,
      int packetOffset = 0) {
    builder.StartTable(3);
    ReplayAction.AddPacket(builder, packetOffset);
    ReplayAction.AddPlayer(builder, player);
    ReplayAction.AddPacketType(builder, packet_type);
    return ReplayAction.EndReplayAction(builder);
  }

  public static void StartReplayAction(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayer(FlatBufferBuilder builder, int player) { builder.AddInt(0, player, 0); }
  public static void AddPacketType(FlatBufferBuilder builder, CardGameUtils.Packets.Duel.ReplayActionPacket packetType) { builder.AddByte(1, (byte)packetType, 0); }
  public static void AddPacket(FlatBufferBuilder builder, int packetOffset) { builder.AddOffset(2, packetOffset, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ReplayAction> EndReplayAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ReplayAction>(o);
  }
  public ReplayActionT UnPack() {
    var _o = new ReplayActionT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ReplayActionT _o) {
    _o.Player = this.Player;
    _o.Packet = new CardGameUtils.Packets.Duel.ReplayActionPacketUnion();
    _o.Packet.Type = this.PacketType;
    switch (this.PacketType) {
      default: break;
      case CardGameUtils.Packets.Duel.ReplayActionPacket.client:
        _o.Packet.Value = this.Packet<CardGameUtils.Packets.Duel.ClientPacket>().HasValue ? this.Packet<CardGameUtils.Packets.Duel.ClientPacket>().Value.UnPack() : null;
        break;
      case CardGameUtils.Packets.Duel.ReplayActionPacket.server:
        _o.Packet.Value = this.Packet<CardGameUtils.Packets.Duel.ServerPacket>().HasValue ? this.Packet<CardGameUtils.Packets.Duel.ServerPacket>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<CardGameUtils.Packets.Duel.ReplayAction> Pack(FlatBufferBuilder builder, ReplayActionT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ReplayAction>);
    var _packet_type = _o.Packet == null ? CardGameUtils.Packets.Duel.ReplayActionPacket.NONE : _o.Packet.Type;
    var _packet = _o.Packet == null ? 0 : CardGameUtils.Packets.Duel.ReplayActionPacketUnion.Pack(builder, _o.Packet);
    return CreateReplayAction(
      builder,
      _o.Player,
      _packet_type,
      _packet);
  }
}

public class ReplayActionT
{
  public int Player { get; set; }
  public CardGameUtils.Packets.Duel.ReplayActionPacketUnion Packet { get; set; }

  public ReplayActionT() {
    this.Player = 0;
    this.Packet = null;
  }
}


static public class ReplayActionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Player*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PacketType*/, 1 /*CardGameUtils.Packets.Duel.ReplayActionPacket*/, 1, false)
      && verifier.VerifyUnion(tablePos, 6, 8 /*Packet*/, CardGameUtils.Packets.Duel.ReplayActionPacketVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
