// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerGetOptionsPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerGetOptionsPacket GetRootAsServerGetOptionsPacket(ByteBuffer _bb) { return GetRootAsServerGetOptionsPacket(_bb, new ServerGetOptionsPacket()); }
  public static ServerGetOptionsPacket GetRootAsServerGetOptionsPacket(ByteBuffer _bb, ServerGetOptionsPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerGetOptionsPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Constants.Location Location { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Constants.Location)__p.bb.Get(o + __p.bb_pos) : CardGameUtils.Constants.Location.UNKNOWN; } }
  public int Uid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CardGameUtils.Shared.CardAction? Options(int j) { int o = __p.__offset(8); return o != 0 ? (CardGameUtils.Shared.CardAction?)(new CardGameUtils.Shared.CardAction()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OptionsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CardGameUtils.Packets.Duel.ServerGetOptionsPacket> CreateServerGetOptionsPacket(FlatBufferBuilder builder,
      CardGameUtils.Constants.Location location = CardGameUtils.Constants.Location.UNKNOWN,
      int uid = 0,
      VectorOffset optionsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    ServerGetOptionsPacket.AddOptions(builder, optionsOffset);
    ServerGetOptionsPacket.AddUid(builder, uid);
    ServerGetOptionsPacket.AddLocation(builder, location);
    return ServerGetOptionsPacket.EndServerGetOptionsPacket(builder);
  }

  public static void StartServerGetOptionsPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddLocation(FlatBufferBuilder builder, CardGameUtils.Constants.Location location) { builder.AddByte(0, (byte)location, 0); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(1, uid, 0); }
  public static void AddOptions(FlatBufferBuilder builder, VectorOffset optionsOffset) { builder.AddOffset(2, optionsOffset.Value, 0); }
  public static VectorOffset CreateOptionsVector(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardAction>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOptionsVectorBlock(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardAction>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOptionsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CardGameUtils.Shared.CardAction>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOptionsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CardGameUtils.Shared.CardAction>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOptionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CardGameUtils.Packets.Duel.ServerGetOptionsPacket> EndServerGetOptionsPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ServerGetOptionsPacket>(o);
  }
  public ServerGetOptionsPacketT UnPack() {
    var _o = new ServerGetOptionsPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerGetOptionsPacketT _o) {
    _o.Location = this.Location;
    _o.Uid = this.Uid;
    _o.Options = new List<CardGameUtils.Shared.CardActionT>();
    for (var _j = 0; _j < this.OptionsLength; ++_j) {_o.Options.Add(this.Options(_j).HasValue ? this.Options(_j).Value.UnPack() : null);}
  }
  public static Offset<CardGameUtils.Packets.Duel.ServerGetOptionsPacket> Pack(FlatBufferBuilder builder, ServerGetOptionsPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ServerGetOptionsPacket>);
    var _options = default(VectorOffset);
    if (_o.Options != null) {
      var __options = new Offset<CardGameUtils.Shared.CardAction>[_o.Options.Count];
      for (var _j = 0; _j < __options.Length; ++_j) { __options[_j] = CardGameUtils.Shared.CardAction.Pack(builder, _o.Options[_j]); }
      _options = CreateOptionsVector(builder, __options);
    }
    return CreateServerGetOptionsPacket(
      builder,
      _o.Location,
      _o.Uid,
      _options);
  }
}

public class ServerGetOptionsPacketT
{
  public CardGameUtils.Constants.Location Location { get; set; }
  public int Uid { get; set; }
  public List<CardGameUtils.Shared.CardActionT> Options { get; set; }

  public ServerGetOptionsPacketT() {
    this.Location = CardGameUtils.Constants.Location.UNKNOWN;
    this.Uid = 0;
    this.Options = null;
  }
}


static public class ServerGetOptionsPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Location*/, 1 /*CardGameUtils.Constants.Location*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Uid*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Options*/, CardGameUtils.Shared.CardActionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
