// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

public enum ServerContent : byte
{
  NONE = 0,
  gameresult = 1,
  getoptions = 2,
  yesno = 3,
  selectcards = 4,
  customselectcards = 5,
  customselectintermediate = 6,
  fieldupdate = 7,
  selectzone = 8,
  showcards = 9,
};

public class ServerContentUnion {
  public ServerContent Type { get; set; }
  public object Value { get; set; }

  public ServerContentUnion() {
    this.Type = ServerContent.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public CardGameUtils.Packets.Duel.ServerGameResultPacketT Asgameresult() { return this.As<CardGameUtils.Packets.Duel.ServerGameResultPacketT>(); }
  public static ServerContentUnion Fromgameresult(CardGameUtils.Packets.Duel.ServerGameResultPacketT _gameresult) { return new ServerContentUnion{ Type = ServerContent.gameresult, Value = _gameresult }; }
  public CardGameUtils.Packets.Duel.ServerGetOptionsPacketT Asgetoptions() { return this.As<CardGameUtils.Packets.Duel.ServerGetOptionsPacketT>(); }
  public static ServerContentUnion Fromgetoptions(CardGameUtils.Packets.Duel.ServerGetOptionsPacketT _getoptions) { return new ServerContentUnion{ Type = ServerContent.getoptions, Value = _getoptions }; }
  public CardGameUtils.Packets.Duel.ServerYesNoPacketT Asyesno() { return this.As<CardGameUtils.Packets.Duel.ServerYesNoPacketT>(); }
  public static ServerContentUnion Fromyesno(CardGameUtils.Packets.Duel.ServerYesNoPacketT _yesno) { return new ServerContentUnion{ Type = ServerContent.yesno, Value = _yesno }; }
  public CardGameUtils.Packets.Duel.ServerSelectCardsPacketT Asselectcards() { return this.As<CardGameUtils.Packets.Duel.ServerSelectCardsPacketT>(); }
  public static ServerContentUnion Fromselectcards(CardGameUtils.Packets.Duel.ServerSelectCardsPacketT _selectcards) { return new ServerContentUnion{ Type = ServerContent.selectcards, Value = _selectcards }; }
  public CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacketT Ascustomselectcards() { return this.As<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacketT>(); }
  public static ServerContentUnion Fromcustomselectcards(CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacketT _customselectcards) { return new ServerContentUnion{ Type = ServerContent.customselectcards, Value = _customselectcards }; }
  public CardGameUtils.Packets.Duel.ServerCustomSelectIntermediatePacketT Ascustomselectintermediate() { return this.As<CardGameUtils.Packets.Duel.ServerCustomSelectIntermediatePacketT>(); }
  public static ServerContentUnion Fromcustomselectintermediate(CardGameUtils.Packets.Duel.ServerCustomSelectIntermediatePacketT _customselectintermediate) { return new ServerContentUnion{ Type = ServerContent.customselectintermediate, Value = _customselectintermediate }; }
  public CardGameUtils.Packets.Duel.ServerFieldUpdatePacketT Asfieldupdate() { return this.As<CardGameUtils.Packets.Duel.ServerFieldUpdatePacketT>(); }
  public static ServerContentUnion Fromfieldupdate(CardGameUtils.Packets.Duel.ServerFieldUpdatePacketT _fieldupdate) { return new ServerContentUnion{ Type = ServerContent.fieldupdate, Value = _fieldupdate }; }
  public CardGameUtils.Packets.Duel.ServerSelectZonePacketT Asselectzone() { return this.As<CardGameUtils.Packets.Duel.ServerSelectZonePacketT>(); }
  public static ServerContentUnion Fromselectzone(CardGameUtils.Packets.Duel.ServerSelectZonePacketT _selectzone) { return new ServerContentUnion{ Type = ServerContent.selectzone, Value = _selectzone }; }
  public CardGameUtils.Packets.Duel.ServerShowCardsPacketT Asshowcards() { return this.As<CardGameUtils.Packets.Duel.ServerShowCardsPacketT>(); }
  public static ServerContentUnion Fromshowcards(CardGameUtils.Packets.Duel.ServerShowCardsPacketT _showcards) { return new ServerContentUnion{ Type = ServerContent.showcards, Value = _showcards }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ServerContentUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ServerContent.gameresult: return CardGameUtils.Packets.Duel.ServerGameResultPacket.Pack(builder, _o.Asgameresult()).Value;
      case ServerContent.getoptions: return CardGameUtils.Packets.Duel.ServerGetOptionsPacket.Pack(builder, _o.Asgetoptions()).Value;
      case ServerContent.yesno: return CardGameUtils.Packets.Duel.ServerYesNoPacket.Pack(builder, _o.Asyesno()).Value;
      case ServerContent.selectcards: return CardGameUtils.Packets.Duel.ServerSelectCardsPacket.Pack(builder, _o.Asselectcards()).Value;
      case ServerContent.customselectcards: return CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket.Pack(builder, _o.Ascustomselectcards()).Value;
      case ServerContent.customselectintermediate: return CardGameUtils.Packets.Duel.ServerCustomSelectIntermediatePacket.Pack(builder, _o.Ascustomselectintermediate()).Value;
      case ServerContent.fieldupdate: return CardGameUtils.Packets.Duel.ServerFieldUpdatePacket.Pack(builder, _o.Asfieldupdate()).Value;
      case ServerContent.selectzone: return CardGameUtils.Packets.Duel.ServerSelectZonePacket.Pack(builder, _o.Asselectzone()).Value;
      case ServerContent.showcards: return CardGameUtils.Packets.Duel.ServerShowCardsPacket.Pack(builder, _o.Asshowcards()).Value;
    }
  }
}



static public class ServerContentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ServerContent)typeId)
    {
      case ServerContent.gameresult:
        result = CardGameUtils.Packets.Duel.ServerGameResultPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.getoptions:
        result = CardGameUtils.Packets.Duel.ServerGetOptionsPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.yesno:
        result = CardGameUtils.Packets.Duel.ServerYesNoPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.selectcards:
        result = CardGameUtils.Packets.Duel.ServerSelectCardsPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.customselectcards:
        result = CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.customselectintermediate:
        result = CardGameUtils.Packets.Duel.ServerCustomSelectIntermediatePacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.fieldupdate:
        result = CardGameUtils.Packets.Duel.ServerFieldUpdatePacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.selectzone:
        result = CardGameUtils.Packets.Duel.ServerSelectZonePacketVerify.Verify(verifier, tablePos);
        break;
      case ServerContent.showcards:
        result = CardGameUtils.Packets.Duel.ServerShowCardsPacketVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
