// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerYesNoPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerYesNoPacket GetRootAsServerYesNoPacket(ByteBuffer _bb) { return GetRootAsServerYesNoPacket(_bb, new ServerYesNoPacket()); }
  public static ServerYesNoPacket GetRootAsServerYesNoPacket(ByteBuffer _bb, ServerYesNoPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerYesNoPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Question { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetQuestionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetQuestionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetQuestionArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<CardGameUtils.Packets.Duel.ServerYesNoPacket> CreateServerYesNoPacket(FlatBufferBuilder builder,
      StringOffset questionOffset = default(StringOffset)) {
    builder.StartTable(1);
    ServerYesNoPacket.AddQuestion(builder, questionOffset);
    return ServerYesNoPacket.EndServerYesNoPacket(builder);
  }

  public static void StartServerYesNoPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddQuestion(FlatBufferBuilder builder, StringOffset questionOffset) { builder.AddOffset(0, questionOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ServerYesNoPacket> EndServerYesNoPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ServerYesNoPacket>(o);
  }
  public ServerYesNoPacketT UnPack() {
    var _o = new ServerYesNoPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerYesNoPacketT _o) {
    _o.Question = this.Question;
  }
  public static Offset<CardGameUtils.Packets.Duel.ServerYesNoPacket> Pack(FlatBufferBuilder builder, ServerYesNoPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ServerYesNoPacket>);
    var _question = _o.Question == null ? default(StringOffset) : builder.CreateString(_o.Question);
    return CreateServerYesNoPacket(
      builder,
      _question);
  }
}

public class ServerYesNoPacketT
{
  public string Question { get; set; }

  public ServerYesNoPacketT() {
    this.Question = null;
  }
}


static public class ServerYesNoPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Question*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
