// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerCustomSelectCardsPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerCustomSelectCardsPacket GetRootAsServerCustomSelectCardsPacket(ByteBuffer _bb) { return GetRootAsServerCustomSelectCardsPacket(_bb, new ServerCustomSelectCardsPacket()); }
  public static ServerCustomSelectCardsPacket GetRootAsServerCustomSelectCardsPacket(ByteBuffer _bb, ServerCustomSelectCardsPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerCustomSelectCardsPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Shared.CardInfo? Cards(int j) { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Shared.CardInfo?)(new CardGameUtils.Shared.CardInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CardsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string Description { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(6); }
  public bool InitialState { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket> CreateServerCustomSelectCardsPacket(FlatBufferBuilder builder,
      VectorOffset cardsOffset = default(VectorOffset),
      StringOffset descriptionOffset = default(StringOffset),
      bool initial_state = false) {
    builder.StartTable(3);
    ServerCustomSelectCardsPacket.AddDescription(builder, descriptionOffset);
    ServerCustomSelectCardsPacket.AddCards(builder, cardsOffset);
    ServerCustomSelectCardsPacket.AddInitialState(builder, initial_state);
    return ServerCustomSelectCardsPacket.EndServerCustomSelectCardsPacket(builder);
  }

  public static void StartServerCustomSelectCardsPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddCards(FlatBufferBuilder builder, VectorOffset cardsOffset) { builder.AddOffset(0, cardsOffset.Value, 0); }
  public static VectorOffset CreateCardsVector(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CardGameUtils.Shared.CardInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCardsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CardGameUtils.Shared.CardInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCardsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(1, descriptionOffset.Value, 0); }
  public static void AddInitialState(FlatBufferBuilder builder, bool initialState) { builder.AddBool(2, initialState, false); }
  public static Offset<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket> EndServerCustomSelectCardsPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket>(o);
  }
  public ServerCustomSelectCardsPacketT UnPack() {
    var _o = new ServerCustomSelectCardsPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerCustomSelectCardsPacketT _o) {
    _o.Cards = new List<CardGameUtils.Shared.CardInfoT>();
    for (var _j = 0; _j < this.CardsLength; ++_j) {_o.Cards.Add(this.Cards(_j).HasValue ? this.Cards(_j).Value.UnPack() : null);}
    _o.Description = this.Description;
    _o.InitialState = this.InitialState;
  }
  public static Offset<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket> Pack(FlatBufferBuilder builder, ServerCustomSelectCardsPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ServerCustomSelectCardsPacket>);
    var _cards = default(VectorOffset);
    if (_o.Cards != null) {
      var __cards = new Offset<CardGameUtils.Shared.CardInfo>[_o.Cards.Count];
      for (var _j = 0; _j < __cards.Length; ++_j) { __cards[_j] = CardGameUtils.Shared.CardInfo.Pack(builder, _o.Cards[_j]); }
      _cards = CreateCardsVector(builder, __cards);
    }
    var _description = _o.Description == null ? default(StringOffset) : builder.CreateString(_o.Description);
    return CreateServerCustomSelectCardsPacket(
      builder,
      _cards,
      _description,
      _o.InitialState);
  }
}

public class ServerCustomSelectCardsPacketT
{
  public List<CardGameUtils.Shared.CardInfoT> Cards { get; set; }
  public string Description { get; set; }
  public bool InitialState { get; set; }

  public ServerCustomSelectCardsPacketT() {
    this.Cards = null;
    this.Description = null;
    this.InitialState = false;
  }
}


static public class ServerCustomSelectCardsPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Cards*/, CardGameUtils.Shared.CardInfoVerify.Verify, false)
      && verifier.VerifyString(tablePos, 6 /*Description*/, false)
      && verifier.VerifyField(tablePos, 8 /*InitialState*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
