// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerGameResultPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ServerGameResultPacket GetRootAsServerGameResultPacket(ByteBuffer _bb) { return GetRootAsServerGameResultPacket(_bb, new ServerGameResultPacket()); }
  public static ServerGameResultPacket GetRootAsServerGameResultPacket(ByteBuffer _bb, ServerGameResultPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerGameResultPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Packets.Duel.GameResult Result { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Packets.Duel.GameResult)__p.bb.GetSbyte(o + __p.bb_pos) : CardGameUtils.Packets.Duel.GameResult.UNKNOWN; } }

  public static Offset<CardGameUtils.Packets.Duel.ServerGameResultPacket> CreateServerGameResultPacket(FlatBufferBuilder builder,
      CardGameUtils.Packets.Duel.GameResult result = CardGameUtils.Packets.Duel.GameResult.UNKNOWN) {
    builder.StartTable(1);
    ServerGameResultPacket.AddResult(builder, result);
    return ServerGameResultPacket.EndServerGameResultPacket(builder);
  }

  public static void StartServerGameResultPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddResult(FlatBufferBuilder builder, CardGameUtils.Packets.Duel.GameResult result) { builder.AddSbyte(0, (sbyte)result, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ServerGameResultPacket> EndServerGameResultPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ServerGameResultPacket>(o);
  }
  public ServerGameResultPacketT UnPack() {
    var _o = new ServerGameResultPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerGameResultPacketT _o) {
    _o.Result = this.Result;
  }
  public static Offset<CardGameUtils.Packets.Duel.ServerGameResultPacket> Pack(FlatBufferBuilder builder, ServerGameResultPacketT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ServerGameResultPacket>);
    return CreateServerGameResultPacket(
      builder,
      _o.Result);
  }
}

public class ServerGameResultPacketT
{
  public CardGameUtils.Packets.Duel.GameResult Result { get; set; }

  public ServerGameResultPacketT() {
    this.Result = CardGameUtils.Packets.Duel.GameResult.UNKNOWN;
  }
}


static public class ServerGameResultPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Result*/, 1 /*CardGameUtils.Packets.Duel.GameResult*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
