// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Packets.Duel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ShownInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ShownInfo GetRootAsShownInfo(ByteBuffer _bb) { return GetRootAsShownInfo(_bb, new ShownInfo()); }
  public static ShownInfo GetRootAsShownInfo(ByteBuffer _bb, ShownInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShownInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CardGameUtils.Shared.CardInfo? Card { get { int o = __p.__offset(4); return o != 0 ? (CardGameUtils.Shared.CardInfo?)(new CardGameUtils.Shared.CardInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string Description { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<CardGameUtils.Packets.Duel.ShownInfo> CreateShownInfo(FlatBufferBuilder builder,
      Offset<CardGameUtils.Shared.CardInfo> cardOffset = default(Offset<CardGameUtils.Shared.CardInfo>),
      StringOffset descriptionOffset = default(StringOffset)) {
    builder.StartTable(2);
    ShownInfo.AddDescription(builder, descriptionOffset);
    ShownInfo.AddCard(builder, cardOffset);
    return ShownInfo.EndShownInfo(builder);
  }

  public static void StartShownInfo(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCard(FlatBufferBuilder builder, Offset<CardGameUtils.Shared.CardInfo> cardOffset) { builder.AddOffset(0, cardOffset.Value, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(1, descriptionOffset.Value, 0); }
  public static Offset<CardGameUtils.Packets.Duel.ShownInfo> EndShownInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CardGameUtils.Packets.Duel.ShownInfo>(o);
  }
  public ShownInfoT UnPack() {
    var _o = new ShownInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ShownInfoT _o) {
    _o.Card = this.Card.HasValue ? this.Card.Value.UnPack() : null;
    _o.Description = this.Description;
  }
  public static Offset<CardGameUtils.Packets.Duel.ShownInfo> Pack(FlatBufferBuilder builder, ShownInfoT _o) {
    if (_o == null) return default(Offset<CardGameUtils.Packets.Duel.ShownInfo>);
    var _card = _o.Card == null ? default(Offset<CardGameUtils.Shared.CardInfo>) : CardGameUtils.Shared.CardInfo.Pack(builder, _o.Card);
    var _description = _o.Description == null ? default(StringOffset) : builder.CreateString(_o.Description);
    return CreateShownInfo(
      builder,
      _card,
      _description);
  }
}

public class ShownInfoT
{
  public CardGameUtils.Shared.CardInfoT Card { get; set; }
  public string Description { get; set; }

  public ShownInfoT() {
    this.Card = null;
    this.Description = null;
  }
}


static public class ShownInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Card*/, CardGameUtils.Shared.CardInfoVerify.Verify, false)
      && verifier.VerifyString(tablePos, 6 /*Description*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
