/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Server
{

	public partial class ArtworkInfo : TBase
	{
		private ArtworkFiletype _filetype;
		private byte[]? _data;

		public ArtworkFiletype Filetype
		{
			get
			{
				return _filetype;
			}
			set
			{
				__isset.@filetype = true;
				this._filetype = value;
			}
		}

		public byte[]? Data
		{
			get
			{
				return _data;
			}
			set
			{
				__isset.@data = true;
				this._data = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @filetype;
			public bool @data;
		}

		public ArtworkInfo()
		{
		}

		public ArtworkInfo DeepCopy()
		{
			var tmp75 = new ArtworkInfo()
			{
			};
			if(__isset.@filetype)
			{
				tmp75.Filetype = this.Filetype;
			}
			tmp75.__isset.@filetype = this.__isset.@filetype;
			if((Data != null) && __isset.@data)
			{
				tmp75.Data = this.Data.ToArray()!;
			}
			tmp75.__isset.@data = this.__isset.@data;
			return tmp75;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I32)
							{
								Filetype = (ArtworkFiletype)await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.String)
							{
								Data = await iprot.ReadBinaryAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp76 = new TStruct("ArtworkInfo");
				await oprot.WriteStructBeginAsync(tmp76, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp77 = new TField();
				if(__isset.@filetype)
				{
					tmp77.Name = "filetype";
					tmp77.Type = TType.I32;
					tmp77.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp77, cancellationToken);
					await oprot.WriteI32Async((int)Filetype, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Data != null) && __isset.@data)
				{
					tmp77.Name = "data";
					tmp77.Type = TType.String;
					tmp77.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp77, cancellationToken);
					await oprot.WriteBinaryAsync(Data, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ArtworkInfo other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@filetype == other.__isset.@filetype) && ((!__isset.@filetype) || (Equals(Filetype, other.Filetype))))
			  && ((__isset.@data == other.__isset.@data) && ((!__isset.@data) || (TCollections.Equals(Data, other.Data))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@filetype)
				{
					hashcode = (hashcode * 397) + Filetype.GetHashCode();
				}
				if((Data != null) && __isset.@data)
				{
					hashcode = (hashcode * 397) + Data.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp78 = new StringBuilder("ArtworkInfo(");
			int tmp79 = 0;
			if(__isset.@filetype)
			{
				if(0 < tmp79++) { _ = tmp78.Append(", "); }
				_ = tmp78.Append("Filetype: ");
				Filetype.ToString(tmp78);
			}
			if((Data != null) && __isset.@data)
			{
				if(0 < tmp79++) { _ = tmp78.Append(", "); }
				_ = tmp78.Append("Data: ");
				Data.ToString(tmp78);
			}
			_ = tmp78.Append(')');
			return tmp78.ToString();
		}
	}

}
