/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Server
{

	public partial class ClientLeave : TBase
	{

		public ClientLeave()
		{
		}

		public ClientLeave DeepCopy()
		{
			var tmp31 = new ClientLeave()
			{
			};
			return tmp31;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp32 = new TStruct("ClientLeave");
				await oprot.WriteStructBeginAsync(tmp32, cancellationToken);
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ClientLeave other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return true;
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp33 = new StringBuilder("ClientLeave(");
			_ = tmp33.Append(')');
			return tmp33.ToString();
		}
	}

}
