/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Server
{

	public partial class ResultFailure : TBase
	{
		private string? _result;

		public string? Result
		{
			get
			{
				return _result;
			}
			set
			{
				__isset.@result = true;
				this._result = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @result;
		}

		public ResultFailure()
		{
		}

		public ResultFailure DeepCopy()
		{
			var tmp129 = new ResultFailure()
			{
			};
			if((Result != null) && __isset.@result)
			{
				tmp129.Result = this.Result!;
			}
			tmp129.__isset.@result = this.__isset.@result;
			return tmp129;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.String)
							{
								Result = await iprot.ReadStringAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp130 = new TStruct("ResultFailure");
				await oprot.WriteStructBeginAsync(tmp130, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp131 = new TField();
				if((Result != null) && __isset.@result)
				{
					tmp131.Name = "result";
					tmp131.Type = TType.String;
					tmp131.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp131, cancellationToken);
					await oprot.WriteStringAsync(Result, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ResultFailure other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@result == other.__isset.@result) && ((!__isset.@result) || (Equals(Result, other.Result))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Result != null) && __isset.@result)
				{
					hashcode = (hashcode * 397) + Result.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp132 = new StringBuilder("ResultFailure(");
			int tmp133 = 0;
			if((Result != null) && __isset.@result)
			{
				if(0 < tmp133++) { _ = tmp132.Append(", "); }
				_ = tmp132.Append("Result: ");
				Result.ToString(tmp132);
			}
			_ = tmp132.Append(')');
			return tmp132.ToString();
		}
	}

}
