/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Server
{

	public partial class ServerStartResultSuccess : TBase
	{
		private string? _room_id;
		private int _port;

		public string? Room_id
		{
			get
			{
				return _room_id;
			}
			set
			{
				__isset.room_id = true;
				this._room_id = value;
			}
		}

		public int Port
		{
			get
			{
				return _port;
			}
			set
			{
				__isset.@port = true;
				this._port = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool room_id;
			public bool @port;
		}

		public ServerStartResultSuccess()
		{
		}

		public ServerStartResultSuccess DeepCopy()
		{
			var tmp117 = new ServerStartResultSuccess()
			{
			};
			if((Room_id != null) && __isset.room_id)
			{
				tmp117.Room_id = this.Room_id!;
			}
			tmp117.__isset.room_id = this.__isset.room_id;
			if(__isset.@port)
			{
				tmp117.Port = this.Port;
			}
			tmp117.__isset.@port = this.__isset.@port;
			return tmp117;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.String)
							{
								Room_id = await iprot.ReadStringAsync(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.I32)
							{
								Port = await iprot.ReadI32Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp118 = new TStruct("ServerStartResultSuccess");
				await oprot.WriteStructBeginAsync(tmp118, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp119 = new TField();
				if((Room_id != null) && __isset.room_id)
				{
					tmp119.Name = "room_id";
					tmp119.Type = TType.String;
					tmp119.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp119, cancellationToken);
					await oprot.WriteStringAsync(Room_id, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if(__isset.@port)
				{
					tmp119.Name = "port";
					tmp119.Type = TType.I32;
					tmp119.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp119, cancellationToken);
					await oprot.WriteI32Async(Port, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerStartResultSuccess other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.room_id == other.__isset.room_id) && ((!__isset.room_id) || (Equals(Room_id, other.Room_id))))
			  && ((__isset.@port == other.__isset.@port) && ((!__isset.@port) || (Equals(Port, other.Port))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if((Room_id != null) && __isset.room_id)
				{
					hashcode = (hashcode * 397) + Room_id.GetHashCode();
				}
				if(__isset.@port)
				{
					hashcode = (hashcode * 397) + Port.GetHashCode();
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp120 = new StringBuilder("ServerStartResultSuccess(");
			int tmp121 = 0;
			if((Room_id != null) && __isset.room_id)
			{
				if(0 < tmp121++) { _ = tmp120.Append(", "); }
				_ = tmp120.Append("Room_id: ");
				Room_id.ToString(tmp120);
			}
			if(__isset.@port)
			{
				if(0 < tmp121++) { _ = tmp120.Append(", "); }
				_ = tmp120.Append("Port: ");
				Port.ToString(tmp120);
			}
			_ = tmp120.Append(')');
			return tmp120.ToString();
		}
	}

}
