/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace CardGameUtils.Packets.Server
{

	public partial class ServerAdditionalCards : TBase
	{
		private long _timestamp;
		private List<Constants.CardInfo>? _cards;

		public long Timestamp
		{
			get
			{
				return _timestamp;
			}
			set
			{
				__isset.@timestamp = true;
				this._timestamp = value;
			}
		}

		public List<Constants.CardInfo>? Cards
		{
			get
			{
				return _cards;
			}
			set
			{
				__isset.@cards = true;
				this._cards = value;
			}
		}


		public Isset __isset;
		public struct Isset
		{
			public bool @timestamp;
			public bool @cards;
		}

		public ServerAdditionalCards()
		{
		}

		public ServerAdditionalCards DeepCopy()
		{
			var tmp56 = new ServerAdditionalCards()
			{
			};
			if(__isset.@timestamp)
			{
				tmp56.Timestamp = this.Timestamp;
			}
			tmp56.__isset.@timestamp = this.__isset.@timestamp;
			if((Cards != null) && __isset.@cards)
			{
				tmp56.Cards = this.Cards.DeepCopy()!;
			}
			tmp56.__isset.@cards = this.__isset.@cards;
			return tmp56;
		}

		public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
		{
			iprot.IncrementRecursionDepth();
			try
			{
				TField field;
				_ = await iprot.ReadStructBeginAsync(cancellationToken);
				while(true)
				{
					field = await iprot.ReadFieldBeginAsync(cancellationToken);
					if(field.Type == TType.Stop)
					{
						break;
					}

					switch(field.ID)
					{
						case 1:
							if(field.Type == TType.I64)
							{
								Timestamp = await iprot.ReadI64Async(cancellationToken);
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						case 2:
							if(field.Type == TType.List)
							{
								{
									var _list57 = await iprot.ReadListBeginAsync(cancellationToken);
									Cards = new List<Constants.CardInfo>(_list57.Count);
									for(int _i58 = 0; _i58 < _list57.Count; ++_i58)
									{
										Constants.CardInfo _elem59;
										_elem59 = new Constants.CardInfo();
										await _elem59.ReadAsync(iprot, cancellationToken);
										Cards.Add(_elem59);
									}
									await iprot.ReadListEndAsync(cancellationToken);
								}
							}
							else
							{
								await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							}
							break;
						default:
							await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
							break;
					}

					await iprot.ReadFieldEndAsync(cancellationToken);
				}

				await iprot.ReadStructEndAsync(cancellationToken);
			}
			finally
			{
				iprot.DecrementRecursionDepth();
			}
		}

		public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
		{
			oprot.IncrementRecursionDepth();
			try
			{
				var tmp60 = new TStruct("ServerAdditionalCards");
				await oprot.WriteStructBeginAsync(tmp60, cancellationToken);
#pragma warning disable IDE0017  // simplified init
				var tmp61 = new TField();
				if(__isset.@timestamp)
				{
					tmp61.Name = "timestamp";
					tmp61.Type = TType.I64;
					tmp61.ID = 1;
					await oprot.WriteFieldBeginAsync(tmp61, cancellationToken);
					await oprot.WriteI64Async(Timestamp, cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
				if((Cards != null) && __isset.@cards)
				{
					tmp61.Name = "cards";
					tmp61.Type = TType.List;
					tmp61.ID = 2;
					await oprot.WriteFieldBeginAsync(tmp61, cancellationToken);
					await oprot.WriteListBeginAsync(new TList(TType.Struct, Cards.Count), cancellationToken);
					foreach(Constants.CardInfo _iter62 in Cards)
					{
						await _iter62.WriteAsync(oprot, cancellationToken);
					}
					await oprot.WriteListEndAsync(cancellationToken);
					await oprot.WriteFieldEndAsync(cancellationToken);
				}
#pragma warning restore IDE0017  // simplified init
				await oprot.WriteFieldStopAsync(cancellationToken);
				await oprot.WriteStructEndAsync(cancellationToken);
			}
			finally
			{
				oprot.DecrementRecursionDepth();
			}
		}

		public override bool Equals(object? that)
		{
			if(that is not ServerAdditionalCards other)
			{
				return false;
			}

			if(ReferenceEquals(this, other))
			{
				return true;
			}

			return ((__isset.@timestamp == other.__isset.@timestamp) && ((!__isset.@timestamp) || (Equals(Timestamp, other.Timestamp))))
			  && ((__isset.@cards == other.__isset.@cards) && ((!__isset.@cards) || (TCollections.Equals(Cards, other.Cards))));
		}

		public override int GetHashCode()
		{
			int hashcode = 157;
			unchecked
			{
				if(__isset.@timestamp)
				{
					hashcode = (hashcode * 397) + Timestamp.GetHashCode();
				}
				if((Cards != null) && __isset.@cards)
				{
					hashcode = (hashcode * 397) + TCollections.GetHashCode(Cards);
				}
			}
			return hashcode;
		}

		public override string ToString()
		{
			var tmp63 = new StringBuilder("ServerAdditionalCards(");
			int tmp64 = 0;
			if(__isset.@timestamp)
			{
				if(0 < tmp64++) { _ = tmp63.Append(", "); }
				_ = tmp63.Append("Timestamp: ");
				Timestamp.ToString(tmp63);
			}
			if((Cards != null) && __isset.@cards)
			{
				if(0 < tmp64++) { _ = tmp63.Append(", "); }
				_ = tmp63.Append("Cards: ");
				Cards.ToString(tmp63);
			}
			_ = tmp63.Append(')');
			return tmp63.ToString();
		}
	}

}
