// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CardGameUtils.Constants
{

public enum PlayerClass : sbyte
{
  UNKNOWN = 0,
  All = 1,
  Cultist = 2,
  Pyromancer = 3,
  Artificer = 4,
  Gladiator = 5,
};


}
